// Built from NH Patient Care Protocols v9.3 (effective 2025-11-07):
// 2.2A Anaphylaxis/Allergic Reaction - Adult (PDF p. 25-26). Pediatric patients go to 2.2P (PDF p. 27).
export default {
  id: 'allergic',
  title: 'Allergic Reaction / Anaphylaxis',
  category: 'Medical',
  nh: '9.3',
  verified: false,
  source: { doc: 'NH Patient Care Protocols v9.3', section: '2.2A', page: 'PDF p. 25-26' },
  keywords: ['allergy', 'allergic', 'anaphylaxis', 'hives', 'bee sting', 'epipen', 'swelling'],
  start: 'peds',
  nodes: {
    peds: {
      type: 'question',
      text: 'Pediatric patient?',
      cite: '2.2A, PDF p. 25',
      answers: [
        { label: 'No: adult', next: 'routine' },
        { label: 'Yes: pediatric', finding: 'Pediatric patient', next: 'pedsInfo' },
      ],
    },
    pedsInfo: {
      type: 'info',
      text: 'Use NH 2.2P Anaphylaxis/Allergic Reaction - Pediatric',
      items: [
        'This adult flow (2.2A) does not apply.',
        'Follow NH 2.2P (PDF p. 27).',
        'Weight-based doses: Meds tab color bands.',
      ],
      cite: '2.2P, PDF p. 27',
      next: 'END',
    },
    routine: {
      type: 'action',
      text: 'Routine Patient Care',
      detail: 'NH 1.0.',
      cite: '2.2A, PDF p. 25',
      level: 'EMT',
      report: 'Routine Patient Care',
      next: 'exposure',
    },
    exposure: {
      type: 'question',
      text: 'Potential allergen exposure?',
      ask: 'What were you exposed to, and when?',
      cite: '2.2A, PDF p. 25',
      answers: [
        { label: 'Food', finding: 'Food exposure', suggest: ['Allergic reaction'], next: 'criteria' },
        { label: 'Sting / bite', finding: 'Sting/bite exposure', suggest: ['Allergic reaction'], next: 'criteria' },
        { label: 'Medication', finding: 'Medication exposure', suggest: ['Allergic reaction'], next: 'criteria' },
        { label: 'Unknown / none found', finding: 'Unknown exposure', next: 'criteria' },
      ],
    },
    criteria: {
      type: 'question',
      text: 'Anaphylaxis: allergen exposure AND any two of these?',
      help: 'Breathing: shortness of breath, wheeze, stridor, cyanosis. Poor perfusion: hypotension, altered mental status, syncope, delayed capillary refill. Skin: hives, itching, extremity swelling, erythema. Gastrointestinal: vomiting, abdominal pain, diarrhea. Do not delay epinephrine for second-line medications such as diphenhydramine.',
      cite: '2.2A, PDF p. 25',
      answers: [
        { label: 'Yes: 2 or more of breathing / perfusion / skin / GI', finding: 'Meets NH anaphylaxis criteria (exposure + 2 systems)', suggest: ['Anaphylaxis'], redFlag: 'Anaphylaxis', next: 'epi' },
        { label: 'Isolated skin symptoms only', finding: 'Isolated skin symptoms of allergic reaction', suggest: ['Allergic reaction'], next: 'diphen' },
        { label: 'Angioedema: deep swelling of face/mouth/upper airway, no other criteria', finding: 'Angioedema', suggest: ['Angioedema'], redFlag: 'Angioedema: prioritize airway', next: 'angio' },
      ],
    },
    epi: {
      type: 'action',
      text: 'Epinephrine IM, anterolateral thigh preferred',
      detail: 'CAUTION: epinephrine comes in different routes and concentrations; re-check dose and concentration before giving. *EMTs must have completed the Ready, Check & Inject training (https://www.nhfaemslearning.org).',
      dose: 'Adult epinephrine autoinjector 0.3 mg IM, OR Epinephrine 1mg/1mL: Administer 0.3 mg (0.3 mL) IM*. If signs and symptoms do not resolve may repeat in 5 minutes.',
      cite: '2.2A, PDF p. 25',
      level: 'EMT',
      critical: true,
      report: 'Epinephrine IM',
      next: 'mcEpi',
    },
    mcEpi: {
      type: 'action',
      text: 'EMT: contact Medical Control for additional epinephrine dosing',
      detail: 'After the one repeat at 5 minutes. AEMT and Paramedic have a standing order to keep repeating (next step).',
      cite: '2.2A, PDF p. 25',
      level: 'EMT',
      report: 'Medical Control contacted re: additional epinephrine',
      next: 'aemtRepeat',
    },
    aemtRepeat: {
      type: 'action',
      text: 'Repeat epinephrine every 5 minutes until signs and symptoms resolve',
      cite: '2.2A, PDF p. 25',
      level: 'AEMT',
      critical: true,
      report: 'Repeat epinephrine IM',
      next: 'wheeze',
    },
    wheeze: {
      type: 'question',
      text: 'Respiratory symptoms / wheezing?',
      cite: '2.2A, PDF p. 25',
      answers: [
        { label: 'Yes', finding: 'Respiratory symptoms / wheezing', next: 'albuterol' },
        { label: 'No', next: 'shock' },
      ],
    },
    albuterol: {
      type: 'action',
      text: 'Albuterol via nebulizer',
      dose: 'Albuterol 2.5mg via nebulizer. Repeat albuterol 2.5 mg, every 5 minutes (4 doses total) via nebulizer.',
      cite: '2.2A, PDF p. 25',
      level: 'EMT',
      report: 'Albuterol nebulizer',
      next: 'shock',
    },
    shock: {
      type: 'question',
      text: 'Signs of shock?',
      cite: '2.2A, PDF p. 25',
      answers: [
        { label: 'Yes', finding: 'Signs of shock', redFlag: 'Anaphylactic shock', next: 'fluid' },
        { label: 'No', next: 'refractory' },
      ],
    },
    fluid: {
      type: 'action',
      text: 'IV fluid per NH 2.22 Shock - Non-Traumatic',
      detail: '2.2A gives no fluid volume; use the amounts in protocol 2.22.',
      cite: '2.2A, PDF p. 25',
      level: 'AEMT',
      critical: true,
      report: 'IV fluid per Shock protocol 2.22',
      next: 'refractory',
    },
    refractory: {
      type: 'question',
      text: 'Refractory to 3 or more doses of IM epinephrine?',
      help: 'For example, persistent hemodynamic compromise or bronchospasm.',
      cite: '2.2A, PDF p. 25',
      answers: [
        { label: 'Yes: still compromised after 3+ IM doses', finding: 'Anaphylaxis refractory to 3+ IM epinephrine doses', redFlag: 'Refractory anaphylaxis', next: 'pushEpi' },
        { label: 'No', next: 'diphen' },
      ],
    },
    pushEpi: {
      type: 'action',
      text: 'Push-dose epinephrine (dilute boluses)',
      detail: 'See Medication Formulary for dilution. Switch to infusion as soon as practical.',
      dose: 'Epinephrine by push dose (dilute boluses - see Medication Formulary) prepare 10 mcg/mL then administer 10 - 20 mcg boluses (1 - 2 mL) every 2 minutes (where feasible, switch to infusion as soon as practical) AND/OR',
      cite: '2.2A, PDF p. 25',
      level: 'Paramedic',
      critical: true,
      report: 'Push-dose epinephrine',
      next: 'epiInfusion',
    },
    epiInfusion: {
      type: 'action',
      text: 'Epinephrine infusion (pump required)',
      dose: 'Epinephrine infusion 2 - 10 micrograms/minute until symptoms resolve, pump required.',
      cite: '2.2A, PDF p. 25',
      level: 'Paramedic',
      critical: true,
      report: 'Epinephrine infusion',
      next: 'diphen',
    },
    diphen: {
      type: 'action',
      text: 'Diphenhydramine (after epinephrine, or for isolated skin symptoms)',
      detail: 'In anaphylaxis, never delay epinephrine for diphenhydramine.',
      dose: 'Diphenhydramine 25 - 50 mg IV/IM/PO.',
      cite: '2.2A, PDF p. 25',
      level: 'Paramedic',
      report: 'Diphenhydramine',
      next: 'extended',
    },
    extended: {
      type: 'question',
      text: 'Extended care situation?',
      help: 'Extended care orders apply only per NH 1.3 Extended Care Guidelines.',
      cite: '2.2A, PDF p. 26',
      answers: [
        { label: 'Yes: extended care', finding: 'Extended care', next: 'ecDiphen' },
        { label: 'No', next: 'END' },
      ],
    },
    ecDiphen: {
      type: 'action',
      text: 'Extended care: diphenhydramine PO',
      dose: 'Diphenhydramine 25 - 50 mg PO. May repeat every 4 - 6 hours as needed; maximum dose of 300 mg in 24 hours.',
      cite: '2.2A, PDF p. 26',
      level: 'EMT',
      report: 'Diphenhydramine PO (extended care)',
      next: 'ecSteroid',
    },
    ecSteroid: {
      type: 'action',
      text: 'Extended care: steroid',
      dose: 'Dexamethasone 10 mg IV/IM/PO OR Methylprednisolone 125 mg IV/IM OR Prednisone 60 mg by mouth.',
      cite: '2.2A, PDF p. 26',
      level: 'Paramedic',
      report: 'Steroid (extended care)',
      next: 'ecFamotidine',
    },
    ecFamotidine: {
      type: 'action',
      text: 'Extended care: famotidine',
      dose: 'Famotidine 20 mg IV/IM/PO.',
      cite: '2.2A, PDF p. 26',
      level: 'Paramedic',
      report: 'Famotidine (extended care)',
      next: 'END',
    },
    angio: {
      type: 'action',
      text: 'Angioedema: prioritize airway management',
      detail: 'Deep swelling of the face, mouth, and upper airway; can be severe. Can be hereditary, idiopathic, or caused by a drug (especially ACE inhibitors, however long the patient has taken them). The diagnosis is clinical.',
      cite: '2.2A, PDF p. 25',
      level: 'Paramedic',
      critical: true,
      report: 'Airway management (angioedema)',
      next: 'txa',
    },
    txa: {
      type: 'action',
      text: 'Angioedema: consider tranexamic acid (TXA)',
      dose: 'Mix 1 gram of TXA in 50-100 mL of 0.9% NaCl; infuse over approximately 10 minutes IV or IO.',
      cite: '2.2A, PDF p. 25',
      level: 'Paramedic',
      report: 'TXA (angioedema)',
      next: 'END',
    },
  },
};
