// NH Patient Care Protocols v9.3, 1.0 Routine Patient Care (PDF pp. 13-15).
// 1.0 has no level headings. Levels: EMR where the item is also in 1.1 EMR Routine Patient Care
// (PDF pp. 16-17); otherwise the lowest level noted on the node.
export default {
  id: 'assessment',
  title: 'Routine Patient Care: Scene Size-Up + Primary Survey',
  category: 'Assessment',
  nh: '9.3',
  verified: false,
  source: { doc: 'NH Patient Care Protocols v9.3', section: '1.0', page: 'PDF p. 13-15' },
  keywords: ['primary', 'scene', 'abc', 'start'],
  start: 'respond',
  nodes: {
    respond: {
      type: 'info',
      text: 'Respond to scene in a safe manner',
      items: [
        'Review dispatch information.',
        'Use lights and sirens and/or pre-emptive devices as appropriate per emergency medical dispatch information and local guidelines.',
        'Use Incident Management/Command System (IM/CS) for all responses and scene management.',
      ],
      cite: '1.0, PDF p. 13',
      next: 'scene',
    },
    scene: {
      type: 'info',
      text: 'Scene arrival and size-up',
      items: [
        'Universal precautions',
        'Scene safety and environmental hazards',
        'Number of patients',
        'Need for additional resources',
        'Bystander safety',
        'Start Mass Casualty Incident procedures as necessary',
      ],
      cite: '1.0, PDF p. 13',
      next: 'moi',
    },
    moi: {
      type: 'question',
      text: 'Mechanism of injury / nature of illness',
      cite: '1.0, PDF p. 13',
      answers: [
        { label: 'Trauma (mechanism of injury)', finding: 'Trauma mechanism', next: 'peds' },
        { label: 'Medical (nature of illness)', finding: 'Medical nature of illness', next: 'peds' },
      ],
    },
    peds: {
      type: 'question',
      text: 'Do pediatric protocols apply?',
      help: 'NH "Pediatric Patient": a child who fits on a length-based resuscitation tape up to 36 kg (79 lbs) or 145 cm (57 in).',
      cite: '1.0, PDF p. 13',
      answers: [
        { label: 'No: adult', next: 'responsive' },
        { label: 'Yes: fits the length-based tape', finding: 'Pediatric patient (fits length-based tape)', redFlag: 'Pediatric patient: use NH pediatric protocols', next: 'responsive' },
      ],
    },
    responsive: {
      type: 'question',
      text: 'Establish responsiveness (AVPU)',
      help: 'Assess level of consciousness appropriate for age. Use the Glasgow Coma Scale for trauma (GCS table, 1.0, PDF p. 15).',
      cite: '1.0, PDF p. 13; AVPU per 1.1, PDF p. 17',
      answers: [
        { label: 'Alert', finding: 'Alert', next: 'general' },
        { label: 'Verbal', finding: 'Responds to verbal only', suggest: ['Altered mental status'], next: 'general' },
        { label: 'Pain', finding: 'Responds to pain only', suggest: ['Altered mental status'], redFlag: 'Responds to pain only', next: 'general' },
        { label: 'Unresponsive', finding: 'Unresponsive', suggest: ['Altered mental status'], redFlag: 'Unresponsive', next: 'pulse' },
      ],
    },
    pulse: {
      type: 'question',
      text: 'Unresponsive: pulse present?',
      help: "Assess the patient's pulse, noting rate, rhythm, and quality.",
      cite: '1.0, PDF p. 14',
      answers: [
        { label: 'Pulse present', next: 'general' },
        { label: 'No pulse', finding: 'Pulseless', redFlag: 'CARDIAC ARREST', suggest: ['Cardiac arrest'], next: 'arrest' },
      ],
    },
    arrest: {
      type: 'info',
      text: 'CARDIAC ARREST: put the phone down.',
      items: [
        'Determine if the DNR/Comfort Care protocol applies (DNR Policy).',
        'CPR and AED defibrillation (EMR scope, 1.1).',
        'Follow NH Cardiac Arrest Protocol - Adult 3.2A, Pediatric 3.2P, or Traumatic Cardiac Arrest 4.10 (not built into this app).',
      ],
      cite: '1.1, PDF p. 17; 1.0, PDF p. 13',
      next: 'END',
    },
    general: {
      type: 'question',
      text: 'General impression',
      help: 'Adult: Appearance (awake, speaking, eye opening, agitated, limp, unresponsive). Work of breathing (labored, noisy, fast, slow, equal chest rise). Circulation to skin (pink, flushed, pale, ashen, cyanosis).',
      cite: '1.0, PDF p. 13',
      answers: [
        { label: 'All three normal', finding: 'General impression: appearance, work of breathing, and skin normal', next: 'dnr' },
        { label: 'Abnormal appearance', finding: 'Abnormal appearance on general impression', redFlag: 'Abnormal general impression', next: 'dnr' },
        { label: 'Abnormal work of breathing', finding: 'Abnormal work of breathing on general impression', redFlag: 'Abnormal general impression', next: 'dnr' },
        { label: 'Abnormal circulation to skin', finding: 'Abnormal skin color on general impression', redFlag: 'Abnormal general impression', next: 'dnr' },
      ],
    },
    dnr: {
      type: 'question',
      text: 'Does the DNR/Comfort Care protocol apply?',
      help: 'Follow the NH DNR Policy.',
      cite: '1.0, PDF p. 13',
      answers: [
        { label: 'No / not known', next: 'airway' },
        { label: 'Yes: follow DNR Policy', finding: 'DNR/Comfort Care applies per DNR Policy', next: 'airway' },
      ],
    },
    airway: {
      type: 'question',
      text: 'Airway patent?',
      cite: '1.0, PDF p. 13',
      answers: [
        { label: 'Yes, patent', next: 'breathing' },
        { label: 'No / compromised', finding: 'Airway compromised', redFlag: 'Airway compromise', next: 'airwayFix' },
      ],
    },
    airwayFix: {
      type: 'action',
      text: 'Open and clear the airway',
      detail: 'Head-tilt/chin-lift, or jaw thrust if you suspect cervical spine injury. Suction as needed. Treat foreign body obstruction per current guidelines. Consider an oropharyngeal airway. 1.0 also lists a nasopharyngeal airway and advanced airway interventions "as appropriate and as trained and credentialed to perform"; these are not in the EMR list (1.1).',
      report: 'Airway opened/maintained',
      level: 'EMR',
      critical: true,
      cite: '1.0, PDF p. 13; 1.1, PDF p. 16',
      next: 'breathing',
    },
    breathing: {
      type: 'question',
      text: 'Breathing: rate, effort, tidal volume, breath sounds',
      help: 'Both skin signs and pulse oximetry matter for hypoxia. Consider capnography (EtCO2) and/or CO-oximetry if available. Assess lung sounds and chest.',
      cite: '1.0, PDF p. 13',
      answers: [
        { label: 'Ineffective breathing', finding: 'Ineffective breathing', redFlag: 'Ineffective breathing', next: 'bvm' },
        { label: 'Effective, but SpO2 ≤ 94% (≤ 90% COPD) or short of breath', finding: 'Low SpO2 or short of breath', suggest: ['Hypoxia'], next: 'oxygen' },
        { label: 'Effective, SpO2 normal, not short of breath', next: 'bleeding' },
      ],
    },
    bvm: {
      type: 'action',
      text: 'Ventilate with 100% oxygen using a bag-valve-mask',
      detail: 'Target adult rate 10 - 12 breaths per minute (child and infant 20 - 30). Titrate rate to goal EtCO2 if available, or to patient condition (e.g., severe asthma, aspirin overdose, traumatic brain injury). EtCO2 normal 35 - 45 mmHg.',
      report: 'BVM ventilation with 100% O2',
      level: 'EMR',
      critical: true,
      cite: '1.0, PDF p. 13 and p. 15; 1.1, PDF p. 16',
      next: 'bleeding',
    },
    oxygen: {
      type: 'action',
      text: 'Administer oxygen',
      dose: 'Give oxygen to maintain saturation ≥ 94 - 98%, as needed',
      detail: 'Caution in COPD patients. If SpO2 is 100%, consider titrating oxygen lower while keeping SpO2 ≥ 94% - 98%. Readings may be false with hypothermia, hypoperfusion, carbon monoxide, sickle cell, vasoconstriction, or nail polish.',
      report: 'O2 titrated to SpO2 94-98%',
      level: 'EMR',
      cite: '1.0, PDF p. 13 and p. 15; EMR scope 1.1, PDF p. 17',
      next: 'bleeding',
    },
    bleeding: {
      type: 'question',
      text: 'Active bleeding?',
      cite: '1.0, PDF p. 14',
      answers: [
        { label: 'No', next: 'perfusion' },
        { label: 'Yes', finding: 'Active hemorrhage', redFlag: 'Active hemorrhage', suggest: ['Hemorrhagic shock'], next: 'bleedControl' },
      ],
    },
    bleedControl: {
      type: 'action',
      text: 'Control active bleeding',
      detail: 'Direct pressure, pressure bandages, tourniquets, or hemostatic bandages. See Hemorrhage Control Protocol 4.4.',
      report: 'Hemorrhage control',
      level: 'EMR',
      critical: true,
      cite: '1.0, PDF p. 14; 1.1, PDF p. 16',
      next: 'perfusion',
    },
    perfusion: {
      type: 'question',
      text: 'Pulse, skin, and blood pressure',
      help: "Pulse rate, rhythm, quality. Skin color, capillary refill, temperature, moisture. Blood pressure.",
      cite: '1.0, PDF p. 14',
      answers: [
        { label: 'Pulse strong; skin warm, dry, pink', finding: 'Skin warm/dry/pink; pulse strong', next: 'iv' },
        { label: 'Pale, cool, clammy; pulse weak/rapid', finding: 'Pale, cool, diaphoretic skin; weak rapid pulse', suggest: ['Shock / hypoperfusion'], redFlag: 'Signs of shock', next: 'iv' },
        { label: 'Hot, flushed', finding: 'Skin hot/flushed', suggest: ['Infection / sepsis', 'Heat emergency'], next: 'iv' },
      ],
    },
    iv: {
      type: 'action',
      text: 'IV access and fluids as appropriate for the condition',
      detail: 'Adults: fluids to maintain systolic BP per Shock Protocols 2.21A, 2.22, 4.6. Consider a blood sample per receiving hospital preference. An IV is a saline lock or line with 0.9% NaCl or Lactated Ringers; "IV" also includes "IO".',
      dose: 'For adult patients with suspected dehydration without shock administer IV fluids as indicated in increments of 250 mL 0.9% NaCl or Lactated Ringers.',
      verify: 'NH 1.0 has no level heading for IV access. AEMT is assigned because IV is not in the EMR list (1.1) and 1.0 does not name a level; confirm with your medical director.',
      report: 'IV access',
      level: 'AEMT',
      cite: '1.0, PDF p. 14',
      next: 'spinal',
    },
    spinal: {
      type: 'question',
      text: 'Spinal motion restriction indicated by Spinal Trauma Protocol 4.7?',
      cite: '1.0, PDF p. 14',
      answers: [
        { label: 'No', next: 'transportMode' },
        { label: 'Yes', finding: 'Spinal motion restriction indicated', next: 'smr' },
      ],
    },
    smr: {
      type: 'action',
      text: 'Spinal motion restriction',
      detail: 'Collar the patient, place flat on the cot, and secure (Spinal Trauma Protocol 4.7). A child who needs it rides in a child safety seat (4.7 and Pediatric Transportation 8.12).',
      report: 'Spinal motion restriction',
      level: 'EMR',
      cite: '1.0, PDF p. 14; 1.1, PDF p. 17',
      next: 'transportMode',
    },
    transportMode: {
      type: 'question',
      text: 'Transport mode',
      help: 'Most patients do not need lights and sirens. Use them only when the patient needs immediate intervention beyond what the crew can do with its supplies and equipment (e.g., STEMI, acute stroke, multi-system trauma). Document lights and sirens use in the PCR.',
      cite: '1.0, PDF p. 14',
      answers: [
        { label: 'Lights and sirens: needs intervention beyond crew capability', finding: 'Emergent transport (lights and sirens) justified', next: 'notify' },
        { label: 'No lights and sirens', finding: 'Non-emergent transport', next: 'notify' },
      ],
    },
    notify: {
      type: 'action',
      text: 'Choose destination and notify the receiving facility early',
      detail: 'The highest-level provider caring for the patient chooses destination and mode, not fire, police, or bystanders. Use Trauma Triage and Transport Decision 8.17 and Air Medical Transport 8.0 as needed.',
      report: 'Receiving facility notified',
      level: 'EMT',
      critical: true,
      cite: '1.0, PDF p. 14 (Transport section is not in EMR 1.1)',
      next: 'secondary',
    },
    secondary: {
      type: 'info',
      text: 'Secondary / focused assessment',
      items: [
        'Chief complaint, history of present illness, prior medical history; open the complaint protocol',
        'Physical assessment for the presentation',
        'Determine level of pain',
        'Consider field tests: cardiac monitoring, blood glucose, temperature, stroke assessment, pulse oximetry, capnography',
        'Dress and bandage lacerations and abrasions',
        'Cover evisceration with an occlusive dressing and cover to prevent heat loss',
        'Stabilize impaled objects; do not remove unless it interferes with CPR or the airway',
        'Vital signs about every 15 minutes (more often if unstable)',
      ],
      cite: '1.0, PDF p. 14',
      next: 'END',
    },
  },
};
