export default {
  id: 'chest-pain',
  title: 'Chest Pain / Suspected ACS',
  category: 'Medical',
  verified: false,
  source: { doc: 'DRAFT from general EMT-B practice; NH v9.2 text not loaded', section: null, page: null },
  keywords: ['chest', 'cardiac', 'acs', 'mi', 'heart attack', 'angina'],
  start: 'onset',
  nodes: {
    onset: {
      type: 'question',
      text: 'Onset',
      ask: 'When did this start? What were you doing?',
      answers: [
        { label: 'Sudden, at rest', finding: 'Sudden onset chest pain at rest', suggest: ['ACS'], next: 'quality' },
        { label: 'With exertion', finding: 'Exertional chest pain', suggest: ['ACS'], next: 'quality' },
        { label: 'Gradual', finding: 'Gradual onset chest pain', next: 'quality' },
      ],
    },
    quality: {
      type: 'question',
      text: 'Quality',
      ask: 'Describe the pain. Is it pressure, sharp, tearing, burning?',
      answers: [
        { label: 'Pressure / squeezing / heavy', finding: 'Pressure-type chest pain', suggest: ['ACS'], next: 'radiation' },
        { label: 'Sharp, worse with breathing', finding: 'Pleuritic chest pain', suggest: ['PE', 'Pneumothorax', 'Pericarditis', 'Pneumonia'], next: 'radiation' },
        { label: 'Tearing, to the back', finding: 'Tearing chest pain radiating to back', suggest: ['Aortic dissection'], redFlag: 'Possible aortic dissection', next: 'radiation' },
        { label: 'Burning', finding: 'Burning chest pain', suggest: ['GI / reflux', 'ACS'], next: 'radiation' },
        { label: 'Reproducible on palpation', finding: 'Pain reproducible on palpation', suggest: ['Musculoskeletal'], next: 'radiation' },
      ],
    },
    radiation: {
      type: 'question',
      text: 'Radiation',
      ask: 'Does the pain go anywhere else?',
      answers: [
        { label: 'Arm / jaw / neck', finding: 'Radiates to arm/jaw/neck', suggest: ['ACS'], next: 'assoc' },
        { label: 'Back', finding: 'Radiates to back', suggest: ['Aortic dissection', 'ACS'], next: 'assoc' },
        { label: 'None', finding: 'Non-radiating', next: 'assoc' },
      ],
    },
    assoc: {
      type: 'question',
      text: 'Associated symptoms (pick the most significant)',
      ask: 'Any shortness of breath, sweating, nausea, dizziness?',
      help: 'Women, diabetics, and elderly patients often present with atypical symptoms (fatigue, nausea, SOB only).',
      answers: [
        { label: 'Diaphoresis', finding: 'Diaphoretic', suggest: ['ACS'], next: 'history' },
        { label: 'Shortness of breath', finding: 'Associated dyspnea', suggest: ['ACS', 'PE', 'CHF'], next: 'history' },
        { label: 'Nausea / vomiting', finding: 'Associated nausea', suggest: ['ACS'], next: 'history' },
        { label: 'Syncope / near-syncope', finding: 'Associated syncope', suggest: ['ACS', 'Arrhythmia', 'Aortic dissection'], redFlag: 'Syncope with chest pain', next: 'history' },
        { label: 'None', finding: 'No associated symptoms', next: 'history' },
      ],
    },
    history: {
      type: 'question',
      text: 'Cardiac history',
      ask: 'Any heart problems, stents, bypass, blood clots? Recent surgery or long travel?',
      answers: [
        { label: 'Prior MI / stents / CABG', finding: 'Cardiac history (MI/stent/CABG)', suggest: ['ACS'], next: 'oxygen' },
        { label: 'Recent surgery, travel, or prior clot', finding: 'PE risk factors', suggest: ['PE'], next: 'oxygen' },
        { label: 'None known', next: 'oxygen' },
      ],
    },
    oxygen: {
      type: 'action',
      text: 'Oxygen only if SpO2 low or signs of hypoxia',
      detail: 'Titrate to target SpO2.',
      verify: 'NH v9.2 SpO2 target range',
      report: 'O2 titrated to SpO2',
      next: 'als',
    },
    als: {
      type: 'action',
      text: 'Request ALS / 12-lead ECG',
      detail: 'Early 12-lead for STEMI identification. Acquire yourself if your agency authorizes EMT 12-lead acquisition.',
      verify: 'NH v9.2 EMT 12-lead acquisition and STEMI destination rules',
      report: 'ALS requested / 12-lead',
      critical: true,
      next: 'asaCheck',
    },
    asaCheck: {
      type: 'question',
      text: 'Aspirin contraindications?',
      ask: 'Are you allergic to aspirin? Any bleeding in your stomach or stool? Did you already take aspirin today?',
      answers: [
        { label: 'None', next: 'asa' },
        { label: 'Allergy / active GI bleed', finding: 'Aspirin contraindicated', next: 'ntgCheck' },
        { label: 'Already took full dose', finding: 'Took aspirin prior to EMS', next: 'ntgCheck' },
        { label: 'Suspected dissection', finding: 'Aspirin withheld: suspected dissection', next: 'ntgCheck' },
      ],
    },
    asa: {
      type: 'action',
      text: 'Aspirin, chewed',
      dose: '324 mg (4 x 81 mg) is the common national dose',
      verify: 'NH v9.2 aspirin dose and indications',
      report: 'Aspirin chewed',
      critical: true,
      next: 'ntgCheck',
    },
    ntgCheck: {
      type: 'question',
      text: 'Nitroglycerin: patient has their own prescription?',
      ask: 'Do you have nitroglycerin prescribed to you? Have you taken Viagra, Cialis, Levitra, or similar in the last 48 hours?',
      help: 'Also hold for low BP, suspected right-sided MI, or HR outside protocol limits.',
      answers: [
        { label: 'Yes, and no contraindications', next: 'ntg' },
        { label: 'No prescription', next: 'transport' },
        { label: 'PDE-5 inhibitor use / low BP', finding: 'Nitro contraindicated', next: 'transport' },
      ],
    },
    ntg: {
      type: 'action',
      text: "Assist with patient's own nitroglycerin",
      dose: '0.4 mg SL, repeat per protocol; recheck BP before each dose',
      verify: 'NH v9.2 SBP threshold, max doses, and whether medical control contact is required',
      report: 'Assisted patient-prescribed NTG SL',
      next: 'transport',
    },
    transport: {
      type: 'action',
      text: 'Transport and notify receiving hospital',
      detail: 'Position of comfort. Reassess vitals and pain after each intervention.',
      verify: 'NH STEMI destination / bypass guidance',
      report: 'Transport initiated, hospital notified',
      critical: true,
      next: 'END',
    },
  },
};
