// NH Patient Care Protocols v9.3, 3.0 Acute Coronary Syndrome - Adult (PDF pp. 79-80).
// Levels are the NH standing-order headings (EMT / Advanced EMT / Paramedic / Paramedic Medical Control).
// The OPQRST questions are assessment prompts for NH's instruction to weigh the likelihood of ACS.
export default {
  id: 'chest-pain',
  title: 'Acute Coronary Syndrome - Adult',
  category: 'Medical',
  nh: '9.3',
  verified: false,
  source: { doc: 'NH Patient Care Protocols v9.3', section: '3.0', page: 'PDF p. 79-80' },
  keywords: ['chest', 'cardiac', 'acs', 'mi', 'heart attack', 'angina'],
  start: 'onset',
  nodes: {
    onset: {
      type: 'question',
      text: 'Onset',
      ask: 'When did this start? What were you doing?',
      help: 'NH 3.0 begins with Routine Patient Care (1.0). Not every chest pain gets aspirin and nitrates: weigh the likelihood of ACS by the symptoms, age, cardiac risk factors, and history.',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: 'Sudden, at rest', finding: 'Sudden onset chest pain at rest', suggest: ['ACS'], next: 'quality' },
        { label: 'With exertion', finding: 'Exertional chest pain', suggest: ['ACS'], next: 'quality' },
        { label: 'Gradual', finding: 'Gradual onset chest pain', next: 'quality' },
      ],
    },
    quality: {
      type: 'question',
      text: 'Quality',
      ask: 'Describe the pain. Is it pressure, sharp, tearing, burning?',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: 'Pressure / squeezing / heavy', finding: 'Pressure-type chest pain', suggest: ['ACS'], next: 'radiation' },
        { label: 'Sharp, worse with breathing', finding: 'Pleuritic chest pain', suggest: ['PE', 'Pneumothorax', 'Pericarditis', 'Pneumonia'], next: 'radiation' },
        { label: 'Tearing, to the back', finding: 'Tearing chest pain radiating to back', suggest: ['Aortic dissection'], redFlag: 'Possible aortic dissection', next: 'radiation' },
        { label: 'Burning', finding: 'Burning chest pain', suggest: ['GI / reflux', 'ACS'], next: 'radiation' },
        { label: 'Reproducible on palpation', finding: 'Pain reproducible on palpation', suggest: ['Musculoskeletal'], next: 'radiation' },
      ],
    },
    radiation: {
      type: 'question',
      text: 'Radiation',
      ask: 'Does the pain go anywhere else?',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: 'Arm / jaw / neck', finding: 'Radiates to arm/jaw/neck', suggest: ['ACS'], next: 'assoc' },
        { label: 'Back', finding: 'Radiates to back', suggest: ['Aortic dissection', 'ACS'], next: 'assoc' },
        { label: 'None', finding: 'Non-radiating', next: 'assoc' },
      ],
    },
    assoc: {
      type: 'question',
      text: 'Associated symptoms (pick the most significant)',
      ask: 'Any shortness of breath, sweating, nausea, weakness, fainting?',
      help: 'NH pearl: ACS patients (especially women and the elderly) may present without chest pain: shortness of breath, weakness, syncope, nausea.',
      cite: '3.0, PDF p. 80',
      answers: [
        { label: 'Diaphoresis', finding: 'Diaphoretic', suggest: ['ACS'], next: 'history' },
        { label: 'Shortness of breath', finding: 'Associated dyspnea', suggest: ['ACS', 'PE', 'CHF'], next: 'history' },
        { label: 'Nausea / vomiting', finding: 'Associated nausea', suggest: ['ACS'], next: 'history' },
        { label: 'Syncope / near-syncope', finding: 'Associated syncope', suggest: ['ACS', 'Arrhythmia', 'Aortic dissection'], redFlag: 'Syncope with chest pain', next: 'history' },
        { label: 'Weakness', finding: 'Associated weakness', suggest: ['ACS'], next: 'history' },
        { label: 'None', finding: 'No associated symptoms', next: 'history' },
      ],
    },
    history: {
      type: 'question',
      text: 'Cardiac history',
      ask: 'Any heart problems, stents, bypass, blood clots? Recent surgery or long travel?',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: 'Prior MI / stents / CABG', finding: 'Cardiac history (MI/stent/CABG)', suggest: ['ACS'], next: 'ecg' },
        { label: 'Recent surgery, travel, or prior clot', finding: 'PE risk factors', suggest: ['PE'], next: 'ecg' },
        { label: 'None known', next: 'ecg' },
      ],
    },
    ecg: {
      type: 'action',
      text: 'Obtain 12-lead ECG within 10 minutes and transmit',
      detail: 'If available and practical. See Protocol 6.0 12-Lead EKG Acquisition. Transmit any 12-lead that reads "Acute MI", "Meets ST Elevation MI Criteria" or similar, or where the interpretation is unclear.',
      verify: 'How to transmit is set by local guidelines (NH 3.0 leaves this to local policy).',
      report: '12-lead ECG obtained and transmitted',
      level: 'EMT',
      critical: true,
      cite: '3.0, PDF p. 79; pearl PDF p. 80',
      next: 'oxygen',
    },
    oxygen: {
      type: 'action',
      text: 'Oxygen only for dyspnea, hypoxia (O2 sat <94%), or signs of heart failure',
      dose: 'at a rate to keep O2 saturation ≥ 94 – 98%',
      report: 'O2 for dyspnea/hypoxia/heart failure, titrated to SpO2 94-98%',
      level: 'EMT',
      cite: '3.0, PDF p. 79',
      next: 'asaCheck',
    },
    asaCheck: {
      type: 'question',
      text: 'Aspirin: any reason to withhold?',
      ask: 'Have you ever had a severe allergic reaction to aspirin or anti-inflammatories like ibuprofen? Any bleeding in your stomach, vomit, or stool? Did you take aspirin in the last 30 minutes, and how much?',
      cite: '3.0, PDF p. 79-80',
      answers: [
        { label: 'None of these', next: 'asa' },
        { label: 'History of anaphylaxis to aspirin or NSAIDs', finding: 'Aspirin withheld: anaphylaxis history to aspirin/NSAIDs', next: 'iv' },
        { label: 'Evidence of active GI bleeding', finding: 'Aspirin withheld: active GI bleeding', next: 'iv' },
        { label: 'Self-administered 324 mg within the last 30 minutes', finding: 'Took aspirin 324 mg within 30 min prior to EMS', next: 'iv' },
      ],
    },
    asa: {
      type: 'action',
      text: 'Aspirin, chewed',
      dose: 'Administer aspirin 324 mg by mouth (chewable), unless patient self administered 324 mg within the last 30 minutes.',
      report: 'Aspirin 324 mg PO chewed',
      level: 'EMT',
      critical: true,
      cite: '3.0, PDF p. 79',
      next: 'iv',
    },
    iv: {
      type: 'action',
      text: 'Establish IV (if feasible, avoid right wrist)',
      detail: 'IV must be established before an AEMT or Paramedic gives nitroglycerin.',
      report: 'IV established',
      level: 'AEMT',
      cite: '3.0, PDF p. 79',
      next: 'ntgCheck',
    },
    ntgCheck: {
      type: 'question',
      text: 'Nitroglycerin: any reason to withhold?',
      ask: 'In the last few days, have you taken Viagra, Revatio, Levitra, Staxyn, Cialis, or Adcirca? Are you on IV Flolan (epoprostenol)?',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: 'None: symptoms persist and systolic BP >100 mmHg', next: 'ntgWhich' },
        { label: 'Phosphodiesterase inhibitor (sildenafil, vardenafil, tadalafil)', finding: 'Nitroglycerin withheld: phosphodiesterase inhibitor use', redFlag: 'No nitro: PDE inhibitor', next: 'pain' },
        { label: 'Receiving IV epoprostenol (Flolan)', finding: 'Nitroglycerin withheld: IV epoprostenol', redFlag: 'No nitro: IV epoprostenol', next: 'pain' },
        { label: 'Systolic BP 100 mmHg or less', finding: 'Nitroglycerin withheld: SBP ≤ 100 mmHg', next: 'pain' },
        { label: 'Symptoms resolved', finding: 'Symptoms resolved; no nitroglycerin', next: 'pain' },
      ],
    },
    ntgWhich: {
      type: 'question',
      text: 'Which nitroglycerin order applies?',
      help: 'EMT: patient\'s own nitroglycerin only. AEMT and Paramedic: SL nitroglycerin after an IV is in place.',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: "EMT: patient's own prescribed nitroglycerin", next: 'ntgOwn' },
        { label: 'AEMT / Paramedic: IV in place', next: 'ntgSL' },
        { label: 'Neither available', finding: 'No nitroglycerin available', next: 'pain' },
      ],
    },
    ntgOwn: {
      type: 'action',
      text: "Help the patient take their own nitroglycerin",
      dose: "Facilitate administration of the patient's own nitroglycerin every 3 – 5 minutes while symptoms persist and systolic BP remains >100 mmHg, to a total of 3 doses.",
      detail: 'Recheck BP before each dose.',
      report: "Assisted patient's own NTG",
      level: 'EMT',
      cite: '3.0, PDF p. 79',
      next: 'pain',
    },
    ntgSL: {
      type: 'action',
      text: 'Nitroglycerin SL',
      dose: 'Nitroglycerin 0.4 mg SL every 3 – 5 minutes while symptoms persist and if systolic BP remains >100 mmHg.',
      detail: 'IV must be established first.',
      verify: 'NH 3.0 gives no maximum number of SL doses at the AEMT/Paramedic level; follow medical control or local policy.',
      report: 'NTG 0.4 mg SL',
      level: 'AEMT',
      cite: '3.0, PDF p. 79',
      next: 'ntgIV',
    },
    ntgIV: {
      type: 'action',
      text: 'Consider IV nitroglycerin if symptoms persist',
      dose: 'Consider IV nitroglycerin at 10 micrograms/minute if symptoms persist. Increase IV nitroglycerin by 10 micrograms/minute every 5 minutes while symptoms persist and systolic BP remains >100 mmHg.',
      detail: 'Two IV lines recommended. IV nitroglycerin must be on an infusion pump.',
      report: 'IV NTG infusion',
      level: 'Paramedic',
      cite: '3.0, PDF p. 79',
      next: 'pain',
    },
    pain: {
      type: 'question',
      text: 'Paramedic: pain control? (systolic BP must stay >100 mmHg)',
      help: 'Fentanyl OR morphine, not both.',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: 'Fentanyl', next: 'fentanyl' },
        { label: 'Morphine', next: 'morphine' },
        { label: 'Not needed / not a Paramedic', next: 'stemi' },
      ],
    },
    fentanyl: {
      type: 'action',
      text: 'Consider fentanyl',
      dose: 'Consider fentanyl 25 – 100 micrograms slow IV push or IM/IN every five minutes up to 300 micrograms and systolic BP remains >100 mmHg',
      report: 'Fentanyl',
      level: 'Paramedic',
      cite: '3.0, PDF p. 79',
      next: 'stemi',
    },
    morphine: {
      type: 'action',
      text: 'Consider morphine',
      dose: 'Consider morphine 2 – 5 mg IV/IM every 5 minutes to a maximum of 15 mg titrated to pain and systolic BP remains >100 mmHg.',
      report: 'Morphine',
      level: 'Paramedic',
      cite: '3.0, PDF p. 79',
      next: 'stemi',
    },
    stemi: {
      type: 'question',
      text: 'Does the 12-lead ECG indicate a STEMI?',
      cite: '3.0, PDF p. 79',
      answers: [
        { label: 'Yes: STEMI', finding: '12-lead indicates STEMI', suggest: ['ACS'], redFlag: 'STEMI', next: 'stemiAlert' },
        { label: 'No / not obtained', next: 'transport' },
      ],
    },
    stemiAlert: {
      type: 'action',
      text: 'STEMI: go to the most appropriate facility and call a "STEMI Alert"',
      detail: 'Choose the facility under local STEMI guidelines/agreements. Notify the receiving facility of a "STEMI Alert".',
      verify: 'Destination is set by local STEMI guidelines/agreements; NH leaves a blank page after 3.0 for the local plan.',
      report: 'STEMI Alert called to receiving facility',
      level: 'EMT',
      critical: true,
      cite: '3.0, PDF p. 79',
      next: 'heparin',
    },
    heparin: {
      type: 'action',
      text: 'Contact Medical Control: heparin for STEMI',
      detail: 'Medical Control may consider this only if STEMI without uncontrolled bleeding or known thrombocytopenia.',
      dose: 'Heparin 60 unit/kg to a maximum of 4000 unit IV bolus.',
      report: 'Medical Control contacted re: heparin',
      level: 'Paramedic',
      cite: '3.0, PDF p. 79',
      next: 'transport',
    },
    transport: {
      type: 'action',
      text: 'Transport and notify receiving facility as early as possible',
      detail: 'Reassess pain and vitals after each intervention. Lights and sirens are justified for STEMI (1.0); document their use.',
      report: 'Transport initiated, hospital notified',
      level: 'EMT',
      critical: true,
      cite: '1.0, PDF p. 14',
      next: 'END',
    },
  },
};
