// NH Patient Care Protocols v9.3: 2.11A Hypoglycemia - Adult (PDF p. 45) and 2.8 Hyperglycemia - Adult & Pediatric (PDF p. 41).
// Pediatric hypoglycemia is NH 2.11P (PDF p. 46).
export default {
  id: 'diabetic',
  title: 'Diabetic Emergency / Hypoglycemia',
  category: 'Medical',
  nh: '9.3',
  verified: false,
  source: { doc: 'NH Patient Care Protocols v9.3', section: '2.11A (with 2.8 Hyperglycemia)', page: 'PDF p. 45 (2.8: PDF p. 41)' },
  keywords: ['diabetic', 'sugar', 'glucose', 'hypoglycemia', 'hyperglycemia', 'ams', 'altered'],
  start: 'peds',
  nodes: {
    peds: {
      type: 'question',
      text: 'Pediatric patient?',
      cite: '2.11A, PDF p. 45; 2.11P, PDF p. 46',
      answers: [
        { label: 'No, adult', next: 'rpc' },
        { label: 'Yes, pediatric', finding: 'Pediatric patient', next: 'pedsInfo' },
      ],
    },
    pedsInfo: {
      type: 'info',
      text: 'Use NH 2.11P Hypoglycemia - Pediatric',
      items: [
        'Pediatric hypoglycemia is NH protocol 2.11P (PDF p. 46). This flow is adult only.',
        'Pediatric hyperglycemia is in NH 2.8 Hyperglycemia - Adult & Pediatric (PDF p. 41).',
        'Weight-based doses: open the Meds tab, Peds color bands (NH Appendix A3).',
      ],
      cite: '2.11P, PDF p. 46',
      next: 'END',
    },
    rpc: {
      type: 'action',
      text: 'Routine Patient Care',
      detail: 'NH Routine Patient Care (1.0).',
      level: 'EMT',
      cite: '2.11A, PDF p. 45',
      report: 'Routine patient care',
      next: 'bgl',
    },
    bgl: {
      type: 'action',
      text: 'Obtain glucose reading',
      detail: 'Enter the value in Vitals.',
      level: 'EMT',
      critical: true,
      cite: '2.11A, PDF p. 45; 2.8, PDF p. 41',
      report: 'Blood glucose obtained',
      next: 'range',
    },
    range: {
      type: 'question',
      text: 'Which NH definition does the patient meet?',
      help: 'Hypoglycemic emergency (2.11A): glucose < 60 mg/dL WITH altered mental status. Hyperglycemia (2.8): blood sugar > 250 mg/dL with signs and symptoms suggesting DKA (weakness, altered mental status, abdominal pain, nausea, vomiting, excessive urination, excessive thirst, fruity breath, fast deep breathing) or HHNS (glucose > 600 mg/dL, profound dehydration, focal or global neuro deficits).',
      cite: '2.11A, PDF p. 45; 2.8, PDF p. 41',
      answers: [
        { label: 'Below 60 with altered mental status', finding: 'Hypoglycemic emergency: glucose < 60 mg/dL with altered mental status', suggest: ['Hypoglycemia'], redFlag: 'Hypoglycemic emergency', next: 'swallow' },
        { label: 'Above 250 with DKA / HHNS signs', finding: 'Hyperglycemia > 250 mg/dL with signs of DKA/HHNS', suggest: ['DKA / HHS', 'Infection / sepsis'], redFlag: 'Hyperglycemia with DKA/HHNS signs', next: 'hyperFluid' },
        { label: 'Neither', finding: 'Glucose does not meet NH hypo/hyperglycemia definitions', suggest: ['Stroke', 'Seizure / postictal', 'Overdose / toxic ingestion', 'Infection / sepsis', 'Head injury'], next: 'neither' },
      ],
    },
    neither: {
      type: 'info',
      text: 'Does not meet the NH hypoglycemia or hyperglycemia definition',
      items: [
        'Continue Routine Patient Care and look for another cause.',
        'Hypoglycemic emergency = glucose < 60 mg/dL with altered mental status (2.11A).',
        'Hyperglycemia = > 250 mg/dL with signs of DKA or HHNS (2.8).',
      ],
      cite: '2.11A, PDF p. 45; 2.8, PDF p. 41',
      next: 'END',
    },
    swallow: {
      type: 'question',
      text: 'Alert enough to swallow AND protect their airway?',
      cite: '2.11A, PDF p. 45',
      answers: [
        { label: 'Yes', next: 'oralGlucose' },
        { label: 'No', finding: 'Unable to swallow/protect airway', redFlag: 'Hypoglycemia: nothing by mouth', next: 'glucagonIN' },
      ],
    },
    oralGlucose: {
      type: 'action',
      text: 'Oral glucose gel or equivalent',
      detail: 'Equivalents: 3 - 4 glucose tablets, 4 oz. fruit juice (e.g. orange juice), non-diet soda, 1 tablespoon of pure New Hampshire maple syrup, sugar, or honey.',
      dose: 'Administer 15 - 30 grams commercially prepared glucose gel or equivalent.',
      verify: 'NH book conflict: protocol 2.11A (PDF p. 45) says "15 - 30 grams"; Appendix A2 formulary (PDF p. 240) prints "15 - 30 mg". This flow uses the protocol text (grams).',
      level: 'EMT',
      critical: true,
      cite: '2.11A, PDF p. 45',
      report: 'Oral glucose given',
      next: 'oralResponse',
    },
    oralResponse: {
      type: 'question',
      text: 'Mental status back to baseline?',
      cite: '2.11A, PDF p. 45',
      answers: [
        { label: 'Yes', finding: 'Mental status returned to baseline after oral glucose', next: 'after' },
        { label: 'No', finding: 'Altered mental status persists after oral glucose', redFlag: 'Persistent AMS after oral glucose', next: 'ivAccess' },
      ],
    },
    glucagonIN: {
      type: 'action',
      text: 'Glucagon: intranasal or auto-injector, if available',
      dose: 'If unable to administer glucose gel or equivalent orally, administer commercially prepared intranasal glucagon or glucagon auto-injector, if available.',
      level: 'EMT',
      critical: true,
      cite: '2.11A, PDF p. 45',
      report: 'Glucagon (intranasal / auto-injector) given',
      next: 'pump',
    },
    pump: {
      type: 'question',
      text: 'Insulin pump AND cannot take oral glucose AND glucagon not available AND ALS not available?',
      help: 'All four must be true. Otherwise leave the pump connected and running.',
      cite: '2.11A, PDF p. 45',
      answers: [
        { label: 'Yes, all true', finding: 'Insulin pump; no oral glucose, glucagon, or ALS available', next: 'removePump' },
        { label: 'No', next: 'ivAccess' },
      ],
    },
    removePump: {
      type: 'action',
      text: 'Remove the insulin pump infusion set',
      detail: 'Leave the pump connected and running if the patient is able to ingest oral glucose or glucagon is available.',
      level: 'EMT',
      critical: true,
      cite: '2.11A, PDF p. 45',
      report: 'Insulin pump infusion set removed',
      next: 'ivAccess',
    },
    ivAccess: {
      type: 'question',
      text: 'AEMT / Paramedic: can you establish IV access?',
      help: 'Intraosseous (IO) dextrose is reserved for hypoglycemic patients with severe altered mental status or active seizures when IV access cannot be obtained.',
      cite: '2.11A, PDF p. 45',
      answers: [
        { label: 'Yes, IV', next: 'd10' },
        { label: 'No IV access', finding: 'Unable to establish IV access', next: 'glucagonIM' },
      ],
    },
    d10: {
      type: 'action',
      text: 'Dextrose 10% IV',
      dose: 'Administer dextrose 10% IV via premixed infusion bag (preferred) or prefilled syringe until mental status returns to baseline and glucose level is greater than 60 mg/dL. IV pump not required.',
      level: 'AEMT',
      critical: true,
      cite: '2.11A, PDF p. 45',
      report: 'D10 IV given',
      next: 'after',
    },
    glucagonIM: {
      type: 'action',
      text: 'Glucagon 1 mg IM',
      dose: 'If unable to establish IV access, administer glucagon 1 mg IM.',
      level: 'AEMT',
      critical: true,
      cite: '2.11A, PDF p. 45',
      report: 'Glucagon 1 mg IM given',
      next: 'recheck',
    },
    recheck: {
      type: 'action',
      text: 'Recheck glucose 15 minutes after glucagon',
      level: 'AEMT',
      critical: true,
      cite: '2.11A, PDF p. 45',
      report: 'Glucose rechecked 15 min after glucagon',
      next: 'repeatQ',
    },
    repeatQ: {
      type: 'question',
      text: 'Glucose still below 60 mg/dL with continued altered mental status?',
      cite: '2.11A, PDF p. 45',
      answers: [
        { label: 'Yes', finding: 'Persistent hypoglycemia with AMS after glucagon', next: 'glucagonRepeat' },
        { label: 'No', next: 'after' },
      ],
    },
    glucagonRepeat: {
      type: 'action',
      text: 'Repeat glucagon 1 mg IM',
      dose: 'May repeat glucagon 1 mg IM if glucose level is < 60 mg/dL with continued altered mental status.',
      level: 'AEMT',
      critical: true,
      cite: '2.11A, PDF p. 45',
      report: 'Glucagon 1 mg IM repeated',
      next: 'after',
    },
    after: {
      type: 'info',
      text: 'After treatment',
      items: [
        'Sulfonylureas (e.g., glyburide, glipizide) last 12 - 60 hours. Corrected patients taking them are at particular risk of recurrent lows and often need admission.',
        'If the patient refuses transport after GCS improves and they are back to baseline, encourage complex carbohydrates (15 grams) and protein (12 - 15 grams), such as peanut butter toast, mixed nuts, milk or cheese.',
        'Causes include medication misuse or overdose, missed meal, infection, heart problems (e.g., MI, arrhythmia), or activity changes (e.g., exercise).',
      ],
      verify: 'NH 2.11A gives no treat-and-release criteria; refusal handling follows local policy / medical control.',
      cite: '2.11A, PDF p. 45',
      next: 'END',
    },
    hyperFluid: {
      type: 'action',
      text: 'Consider IV fluid bolus (adult)',
      dose: 'ADULT: Administer 1000 mL IV bolus of IV fluid. May repeat 500 mL fluid bolus once.',
      level: 'AEMT',
      cite: '2.8, PDF p. 41',
      report: 'IV fluid bolus for hyperglycemia',
      next: 'oralFluids',
    },
    oralFluids: {
      type: 'action',
      text: 'Extended care only: oral water if not vomiting',
      detail: 'NH lists this under EMT/AEMT/Paramedic EXTENDED CARE ORDERS. Patient must be alert enough to swallow and protect airway.',
      dose: 'Oral fluids: if the patient is not vomiting, provide oral hydration with water.',
      level: 'EMT',
      cite: '2.8, PDF p. 41',
      report: 'Oral hydration with water (extended care)',
      next: 'END',
    },
  },
};
