export default {
  id: 'diabetic',
  title: 'Diabetic Emergency / Hypoglycemia',
  category: 'Medical',
  verified: false,
  source: { doc: 'DRAFT from general EMT-B practice; NH v9.3 text not loaded', section: null, page: null },
  keywords: ['diabetic', 'sugar', 'glucose', 'hypoglycemia', 'hyperglycemia', 'ams', 'altered'],
  start: 'bgl',
  nodes: {
    bgl: {
      type: 'action',
      text: 'Check blood glucose',
      detail: 'Enter the value in Vitals.',
      report: 'BGL checked',
      critical: true,
      next: 'range',
    },
    range: {
      type: 'question',
      text: 'Glucose result',
      answers: [
        { label: 'Low (below protocol threshold)', finding: 'Hypoglycemia', suggest: ['Hypoglycemia'], next: 'swallow' },
        { label: 'Normal', finding: 'Normal glucose', suggest: ['Stroke', 'Seizure / postictal', 'Overdose / toxic ingestion', 'Infection / sepsis', 'Head injury'], next: 'normal' },
        { label: 'High', finding: 'Hyperglycemia', suggest: ['DKA / HHS', 'Infection / sepsis'], next: 'high' },
      ],
    },
    swallow: {
      type: 'question',
      text: 'Can the patient follow commands, swallow, and protect their airway?',
      answers: [
        { label: 'Yes', next: 'oralGlucose' },
        { label: 'No', finding: 'Unable to protect airway', redFlag: 'Hypoglycemia, unable to take oral glucose', next: 'als' },
      ],
    },
    oralGlucose: {
      type: 'action',
      text: 'Oral glucose',
      dose: '15 g tube is the common national dose',
      verify: 'NH v9.3 hypoglycemia threshold and oral glucose dose/repeat',
      report: 'Oral glucose given',
      critical: true,
      next: 'recheck',
    },
    recheck: {
      type: 'action',
      text: 'Re-check glucose and mental status',
      verify: 'NH v9.3 recheck interval',
      report: 'BGL rechecked',
      critical: true,
      next: 'refusal',
    },
    refusal: {
      type: 'info',
      text: 'If the patient improves and wants to refuse transport',
      items: ['Follow NH v9.3 treat-and-release / refusal criteria', 'Oral hypoglycemic agents (sulfonylureas) and long-acting insulin cause recurrent lows', 'Must eat a meal; responsible adult present'],
      verify: 'NH v9.3 hypoglycemia refusal criteria',
      next: 'END',
    },
    als: {
      type: 'action',
      text: 'Request ALS (IV/IM glucose or glucagon); manage airway; recovery position',
      detail: 'Nothing by mouth.',
      verify: 'Whether NH v9.3 authorizes EMT glucagon',
      report: 'ALS requested for hypoglycemia, airway managed',
      critical: true,
      next: 'END',
    },
    normal: {
      type: 'info',
      text: 'Glucose is not the cause. Look further.',
      items: ['Run Stroke protocol (BE-FAST)', 'Check pupils, medication bottles, trauma to head', 'Temperature / signs of infection'],
      next: 'END',
    },
    high: {
      type: 'info',
      text: 'Hyperglycemia',
      items: ['Signs of DKA: fruity breath, deep rapid breathing, vomiting, dehydration', 'Supportive care, ALS for fluids', 'Transport'],
      next: 'END',
    },
  },
};
