// NH Patient Care Protocols v9.3: 2.17A Opioid Overdose - Adult (PDF p. 57).
// Pediatric is NH 2.17P (PDF p. 58). Other poisonings: NH 2.19.
export default {
  id: 'opioid',
  title: 'Suspected Opioid Overdose',
  category: 'Medical',
  nh: '9.3',
  verified: false,
  source: { doc: 'NH Patient Care Protocols v9.3', section: '2.17A', page: 'PDF p. 57' },
  keywords: ['overdose', 'od', 'opioid', 'heroin', 'fentanyl', 'narcan', 'naloxone', 'unresponsive'],
  start: 'peds',
  nodes: {
    peds: {
      type: 'question',
      text: 'Pediatric patient?',
      cite: '2.17A, PDF p. 57; 2.17P, PDF p. 58',
      answers: [
        { label: 'No, adult', next: 'pulse' },
        { label: 'Yes, pediatric', finding: 'Pediatric patient', next: 'pedsInfo' },
      ],
    },
    pedsInfo: {
      type: 'info',
      text: 'Use NH 2.17P Opioid Overdose - Pediatric',
      items: [
        'Pediatric opioid overdose is NH protocol 2.17P (PDF p. 58). This flow is adult only.',
        'Weight-based doses: open the Meds tab, Peds color bands (NH Appendix A3).',
      ],
      cite: '2.17P, PDF p. 58',
      next: 'END',
    },
    pulse: {
      type: 'question',
      text: 'Pulse present?',
      cite: '3.2A, PDF p. 84',
      answers: [
        { label: 'Yes', next: 'rpc' },
        { label: 'No', finding: 'Pulseless', redFlag: 'CARDIAC ARREST', suggest: ['Cardiac arrest'], next: 'arrest' },
      ],
    },
    arrest: {
      type: 'info',
      text: 'Cardiac arrest: go to NH 3.2A Cardiac Arrest - Adult',
      items: ['NH 3.2A: Routine Patient Care with focus on high performance CPR, immediate chest compressions, AED as soon as possible.'],
      cite: '3.2A, PDF p. 84',
      next: 'END',
    },
    rpc: {
      type: 'action',
      text: 'Routine Patient Care',
      detail: 'NH Routine Patient Care (1.0).',
      level: 'EMR',
      cite: '2.17A, PDF p. 57',
      report: 'Routine patient care',
      next: 'bystander',
    },
    bystander: {
      type: 'action',
      text: 'Find out and document if bystander naloxone was given',
      level: 'EMR',
      cite: '2.17A, PDF p. 57',
      report: 'Bystander naloxone status documented',
      next: 'signs',
    },
    signs: {
      type: 'question',
      text: 'Signs of hypoventilation from opioid intoxication?',
      help: 'Signs and symptoms can include respiratory depression, apnea, altered mental status and/or pinpoint pupils.',
      cite: '2.17A, PDF p. 57',
      answers: [
        { label: 'Yes', finding: 'Hypoventilation, suspected opioid intoxication', suggest: ['Opioid overdose'], redFlag: 'Respiratory depression', next: 'route' },
        { label: 'No, breathing adequately', finding: 'Adequate respirations', next: 'monitor' },
        { label: 'Suspect a substance other than an opioid', finding: 'Suspected non-opioid poisoning/overdose', suggest: ['Overdose / toxic ingestion', 'Mixed ingestion'], next: 'poison' },
      ],
    },
    poison: {
      type: 'info',
      text: 'Non-opioid poisoning or overdose: use NH 2.19 Poisoning/Substance Abuse/Overdose',
      items: ['NH 2.17A: if you suspect a poisoning or overdose by any other substance than an opioid, see the Poisoning and Overdose Protocol 2.19.'],
      cite: '2.17A, PDF p. 57',
      next: 'END',
    },
    route: {
      type: 'question',
      text: 'Naloxone route',
      help: 'Give for hypoventilation. Goal: respiratory depression resolves, not necessarily return of consciousness. Maximum 10 mg total.',
      cite: '2.17A, PDF p. 57',
      answers: [
        { label: 'Intranasal (EMR/EMT)', next: 'naloxoneIN' },
        { label: 'IV (AEMT/Paramedic)', next: 'naloxoneIV' },
        { label: 'IM (AEMT/Paramedic)', next: 'naloxoneIM' },
      ],
    },
    naloxoneIN: {
      type: 'action',
      text: 'Naloxone intranasal',
      detail: 'IN naloxone may take up to 10 minutes to work. Repeat only after enough time has passed to see the effect.',
      dose: 'Naloxone 1 mg (1 mL) per nostril (IN) via prefilled syringe and atomizer for a total of 2 mg OR Naloxone 4 mg (0.5 mL) commercially prepared nasal spray. Repeat every 5 - 10 minutes (maximum 10 mg) until respiratory depression resolves and not necessarily until return of consciousness.',
      level: 'EMR',
      critical: true,
      cite: '2.17A, PDF p. 57',
      report: 'Naloxone IN',
      next: 'response',
    },
    naloxoneIV: {
      type: 'action',
      text: 'Naloxone IV',
      dose: 'Naloxone 0.4 - 2.0 mg IV, repeat every 2 - 3 minutes (maximum 10 mg) until respiratory depression resolves and not necessarily until return of consciousness.',
      level: 'AEMT',
      critical: true,
      cite: '2.17A, PDF p. 57',
      report: 'Naloxone IV',
      next: 'response',
    },
    naloxoneIM: {
      type: 'action',
      text: 'Naloxone IM',
      dose: 'Naloxone 0.4 - 2.0 mg IM, repeat every 5 - 10 minutes (maximum 10 mg) until respiratory depression resolves and not necessarily until return of consciousness.',
      level: 'AEMT',
      critical: true,
      cite: '2.17A, PDF p. 57',
      report: 'Naloxone IM',
      next: 'response',
    },
    response: {
      type: 'question',
      text: 'Respiratory depression resolved?',
      help: 'Repeat interval: IN every 5 - 10 min; IV every 2 - 3 min; IM every 5 - 10 min. Maximum 10 mg total. Capnography may help monitor breathing and titrate to the lowest effective dose (Capnography Procedure 6.3).',
      cite: '2.17A, PDF p. 57',
      answers: [
        { label: 'Yes', finding: 'Respiratory depression resolved after naloxone', suggest: ['Opioid overdose'], next: 'agitation' },
        { label: 'No: repeat dose (10 mg max not reached)', finding: 'Persistent respiratory depression after naloxone', redFlag: 'Persistent respiratory depression', next: 'route' },
        { label: 'No: 10 mg maximum reached', finding: 'No response to naloxone at 10 mg maximum', suggest: ['Mixed ingestion', 'Hypoglycemia', 'Head injury'], redFlag: 'No response to naloxone (10 mg max)', next: 'agitation' },
      ],
    },
    agitation: {
      type: 'info',
      text: 'Caution after naloxone',
      items: [
        'Patient may become agitated or violent from opioid withdrawal/hypoxia.',
        'Patient may have used more than one substance; reversing the opiate may unmask other substances, which could lead to violence or other signs and symptoms.',
      ],
      cite: '2.17A, PDF p. 57',
      next: 'monitor',
    },
    monitor: {
      type: 'action',
      text: 'Monitor for recurrent respiratory depression and decreased mental status',
      detail: 'Naloxone reversal is limited and may end within an hour; some opioids are extended release and last longer.',
      level: 'EMR',
      critical: true,
      cite: '2.17A, PDF p. 57',
      report: 'Monitored for recurrent respiratory depression',
      next: 'kit',
    },
    kit: {
      type: 'info',
      text: 'Naloxone leave-behind kit (if your service stocks them)',
      items: [
        'Give instructions on use and direction to area resources, including the NH Statewide Addiction Crisis Line 211.',
        'Leave-behind kits must be separate from the naloxone used for patient care.',
        'Do not leave a kit where the patient has a known allergy to naloxone or kit constituents.',
      ],
      verify: 'Local policy: NH says EMS units "may choose" to stock leave-behind kits; whether JRMA does is a service decision.',
      cite: '2.17A, PDF p. 57',
      next: 'END',
    },
  },
};
