// Built from NH Patient Care Protocols v9.3 (effective 2025-11-07):
// 2.3A Asthma, COPD, RAD - Adult (PDF p. 28), 3.3 Congestive Heart Failure (Pulmonary Edema) (PDF p. 89),
// 5.4 CPAP (PDF p. 119-120). Pediatric patients go to 2.3P (PDF p. 29-30).
export default {
  id: 'respiratory',
  title: 'Respiratory Distress',
  category: 'Medical',
  nh: '9.3',
  verified: false,
  source: { doc: 'NH Patient Care Protocols v9.3', section: '2.3A; 3.3; 5.4', page: 'PDF p. 28; 89; 119-120' },
  keywords: ['sob', 'shortness of breath', 'asthma', 'copd', 'chf', 'breathing', 'dyspnea'],
  start: 'peds',
  nodes: {
    peds: {
      type: 'question',
      text: 'Pediatric patient?',
      cite: '2.3A, PDF p. 28',
      answers: [
        { label: 'No: adult', next: 'routine' },
        { label: 'Yes: pediatric', finding: 'Pediatric patient', next: 'pedsInfo' },
      ],
    },
    pedsInfo: {
      type: 'info',
      text: 'Use NH 2.3P Asthma/Bronchiolitis/Croup - Pediatric Respiratory Distress',
      items: [
        'This adult flow (2.3A / 3.3) does not apply.',
        'Follow NH 2.3P (PDF p. 29-30).',
        'Weight-based doses: Meds tab color bands.',
      ],
      cite: '2.3P, PDF p. 29',
      next: 'END',
    },
    routine: {
      type: 'action',
      text: 'Routine Patient Care',
      detail: 'NH 1.0. Allow the patient their position of comfort to maximize breathing effort.',
      cite: '2.3A, PDF p. 28',
      level: 'EMT',
      report: 'Routine Patient Care',
      next: 'severity',
    },
    severity: {
      type: 'question',
      text: 'How many words can the patient speak per breath?',
      cite: '2.3A, PDF p. 28',
      answers: [
        { label: 'Full sentences', finding: 'Speaking full sentences', next: 'lungs' },
        { label: 'Short phrases', finding: 'Speaking in short phrases', next: 'lungs' },
        { label: '1-2 words / cannot speak', finding: '1-2 word dyspnea', redFlag: 'Severe respiratory distress', next: 'lungs' },
      ],
    },
    lungs: {
      type: 'question',
      text: 'Lung sounds',
      cite: '2.3A, PDF p. 28',
      answers: [
        { label: 'Wheezes', finding: 'Wheezing', suggest: ['Asthma exacerbation', 'COPD exacerbation', 'Anaphylaxis'], next: 'path' },
        { label: 'Crackles / rales', finding: 'Crackles', suggest: ['CHF / pulmonary edema', 'Pneumonia'], next: 'path' },
        { label: 'Silent chest / little air movement', finding: 'Silent chest', suggest: ['Asthma exacerbation', 'COPD exacerbation'], redFlag: 'Silent chest: severe bronchospasm, impending respiratory failure', next: 'path' },
        { label: 'Diminished one side', finding: 'Unilateral diminished breath sounds', suggest: ['Pneumothorax', 'Pneumonia'], redFlag: 'Unilateral diminished breath sounds: pneumothorax is a CPAP contraindication', next: 'path' },
        { label: 'Stridor', finding: 'Stridor', suggest: ['Upper airway obstruction', 'Anaphylaxis'], redFlag: 'Stridor', next: 'path' },
        { label: 'Clear', finding: 'Lung sounds clear', next: 'path' },
      ],
    },
    path: {
      type: 'question',
      text: 'Which NH protocol fits?',
      ask: 'Do you have asthma, COPD/emphysema, or heart failure? Is this like before?',
      help: 'Hives, swelling, or allergen exposure: use the Allergic Reaction / Anaphylaxis protocol (NH 2.2A).',
      cite: '2.3A, PDF p. 28',
      answers: [
        { label: 'Asthma / COPD / RAD (2.3A)', finding: 'History or picture of asthma/COPD/RAD', suggest: ['Asthma exacerbation', 'COPD exacerbation'], next: 'o2' },
        { label: 'CHF / pulmonary edema (3.3)', finding: 'History or picture of CHF / pulmonary edema', suggest: ['CHF / pulmonary edema'], next: 'chfPosition' },
        { label: 'Other / unclear', next: 'cpapCheck' },
      ],
    },

    // ---- 2.3A Asthma, COPD, RAD - Adult ----
    o2: {
      type: 'action',
      text: 'Oxygen: keep SpO2 94 - 98% (90% in COPD)',
      detail: 'Increase the oxygen rate with caution. Watch for fatigue, decreased mentation, and respiratory failure.',
      dose: 'Attempt to keep oxygen saturation between 94 - 98% (90% in COPD)',
      cite: '2.3A, PDF p. 28',
      level: 'EMT',
      critical: true,
      report: 'O2 titrated to SpO2 target',
      next: 'bronch',
    },
    bronch: {
      type: 'action',
      text: 'Bronchodilator: albuterol MDI, DuoNeb, and/or albuterol neb',
      detail: 'Pick one: MDI OR DuoNeb; albuterol neb may be used and/or. Repeat for continued symptoms.',
      dose: 'Albuterol metered-dose inhaler (MDI) 4 - 6 puffs (with spacer, if available). May repeat every 5 minutes for continued symptoms OR Ipratropium bromide 0.5 mg and albuterol 2.5 mg (DuoNeb) via nebulizer. May repeat every 5 minutes for continued symptoms (maximum 3 doses); AND/OR Albuterol 2.5 mg via nebulizer. May repeat every 5 minutes for continued symptoms.',
      cite: '2.3A, PDF p. 28',
      level: 'EMT',
      critical: true,
      report: 'Bronchodilator given',
      next: 'severeAsthma',
    },
    severeAsthma: {
      type: 'question',
      text: 'Severe ASTHMA (not COPD) not responding to treatment?',
      help: 'NH 2.3A: epinephrine is for severe asthma only.',
      cite: '2.3A, PDF p. 28',
      answers: [
        { label: 'Yes: severe asthma, not responding', finding: 'Severe asthma not responding to bronchodilators', redFlag: 'Severe asthma not responding to treatment', next: 'epiAsthma' },
        { label: 'No', next: 'steroid' },
      ],
    },
    epiAsthma: {
      type: 'action',
      text: 'Epinephrine IM for severe asthma',
      dose: 'Epinephrine autoinjector 0.3 mg IM (preferred) OR epinephrine (1 mg/mL) 0.3 mg (0.3 mL) IM.',
      cite: '2.3A, PDF p. 28',
      level: 'AEMT',
      critical: true,
      report: 'Epinephrine IM (severe asthma)',
      next: 'mcAsthma',
    },
    mcAsthma: {
      type: 'action',
      text: 'Contact Medical Control for additional epinephrine doses',
      cite: '2.3A, PDF p. 28',
      level: 'AEMT',
      report: 'Medical Control contacted re: additional epinephrine',
      next: 'steroid',
    },
    steroid: {
      type: 'action',
      text: 'Steroid: methylprednisolone OR dexamethasone',
      dose: 'Methylprednisolone 125 mg IV/IM OR Dexamethasone 10 mg PO/IM/IV.',
      cite: '2.3A, PDF p. 28',
      level: 'Paramedic',
      report: 'Steroid given',
      next: 'respond',
    },
    respond: {
      type: 'question',
      text: 'Responding to treatment?',
      cite: '2.3A, PDF p. 28',
      answers: [
        { label: 'Yes: improving', finding: 'Improving with treatment', next: 'END' },
        { label: 'No / impending respiratory failure', finding: 'Not responding / impending respiratory failure', redFlag: 'Not responding to treatment / impending respiratory failure', next: 'mag' },
      ],
    },
    mag: {
      type: 'action',
      text: 'Magnesium sulfate IV (non-responders)',
      detail: 'Paramedic may also consider BiPAP (NH Procedure 5.3) for non-responders or impending respiratory failure. EMT/AEMT: continue nebulizers and go to CPAP (next).',
      dose: 'Magnesium sulfate 2 grams in 100 ml NS given IV over 10 minutes.',
      cite: '2.3A, PDF p. 28',
      level: 'Paramedic',
      report: 'Magnesium sulfate IV',
      next: 'cpapCheck',
    },

    // ---- 3.3 Congestive Heart Failure (Pulmonary Edema) ----
    chfPosition: {
      type: 'action',
      text: 'Semi-sitting or full sitting position',
      cite: '3.3, PDF p. 89',
      level: 'EMT',
      critical: true,
      report: 'Positioned sitting',
      next: 'ecg',
    },
    ecg: {
      type: 'action',
      text: '12-lead ECG, if available',
      cite: '3.3, PDF p. 89',
      level: 'EMT',
      report: '12-lead ECG',
      next: 'iv',
    },
    iv: {
      type: 'action',
      text: 'Establish IV access',
      cite: '3.3, PDF p. 89',
      level: 'AEMT',
      report: 'IV access',
      next: 'pde',
    },
    pde: {
      type: 'question',
      text: 'Any reason to avoid nitroglycerin?',
      ask: 'In the last 2 days, have you taken Viagra, Revatio, Levitra, Staxyn, Cialis, or Adcirca? Are you on IV Flolan?',
      help: 'Avoid nitroglycerin with a phosphodiesterase inhibitor within 48 hours (sildenafil, vardenafil, tadalafil) or IV epoprostenol (Flolan).',
      cite: '3.3, PDF p. 89',
      answers: [
        { label: 'No: none of these', finding: 'No PDE inhibitor in 48 h, no IV epoprostenol', next: 'ownNtg' },
        { label: 'Yes: PDE inhibitor in 48 h or IV Flolan', finding: 'PDE inhibitor within 48 h or IV epoprostenol', redFlag: 'Avoid nitroglycerin (PDE inhibitor / IV epoprostenol)', next: 'cpapCheck' },
      ],
    },
    ownNtg: {
      type: 'action',
      text: "Help patient take their own nitroglycerin",
      detail: "If the patient's own nitroglycerin gave no relief, consider loss of potency due to age.",
      dose: "Facilitate administration of the patient's own nitroglycerin every 5 minutes while symptoms persist and systolic BP is > 140 mmHg.",
      cite: '3.3, PDF p. 89',
      level: 'EMT',
      report: "Patient's own nitroglycerin",
      next: 'aemtNtg',
    },
    aemtNtg: {
      type: 'action',
      text: 'Known CHF history: nitroglycerin SL by systolic BP',
      detail: 'Only for patients with a known history of congestive heart failure. Assess blood pressure every 3 - 5 minutes during nitroglycerin administration.',
      dose: 'For systolic BP of 140 - 160 mmHg: nitroglycerin 0.4 mg SL. For systolic BP of 160 - 200 mmHg: nitroglycerin 0.8 mg SL (2 tabs/sprays). For systolic BP > 200 mmHg: nitroglycerin 1.2 mg SL (3 tabs/sprays). The above doses may be repeated every 5 minutes until symptomatic improvement or systolic BP of 120 - 140 mmHg.',
      cite: '3.3, PDF p. 89',
      level: 'AEMT',
      critical: true,
      report: 'Nitroglycerin SL',
      next: 'paraNtg',
    },
    paraNtg: {
      type: 'action',
      text: 'Consider IV nitroglycerin infusion by systolic BP',
      detail: 'Two (2) IV lines are recommended. IV nitroglycerin infusions must be given using an infusion pump.',
      dose: 'For systolic BP of 140 - 160 mmHg: IV nitroglycerin start at 50 micrograms/minute. For systolic BP of 160 - 200 mmHg: IV nitroglycerin start at 100 micrograms/minute. For systolic BP > 200 mmHg: IV nitroglycerin start at 200 micrograms/minute. Titrate 5 - 10 mcg/min every 3 - 5 minutes until symptomatic improvement or systolic BP of 120 - 140 mmHg.',
      cite: '3.3, PDF p. 89',
      level: 'Paramedic',
      report: 'Nitroglycerin infusion',
      next: 'cpapCheck',
    },

    // ---- 5.4 CPAP ----
    cpapCheck: {
      type: 'question',
      text: 'CPAP: severe respiratory distress and no absolute contraindication?',
      help: 'Indication: spontaneously breathing patient in severe respiratory distress. Do NOT use if: cardiac/respiratory arrest; agonal respirations; unresponsive; vomiting and/or active upper GI bleed; respiratory distress secondary to trauma; suspicion of pneumothorax. Use cautiously if unable to follow commands or agitated/combative.',
      cite: '5.4, PDF p. 119',
      answers: [
        { label: 'Yes: severe distress, no contraindication', finding: 'Meets CPAP indication', next: 'cpap' },
        { label: 'Absolute contraindication present', finding: 'CPAP contraindicated', redFlag: 'CPAP contraindicated', next: 'END' },
        { label: 'Not in severe distress', next: 'END' },
      ],
    },
    cpap: {
      type: 'action',
      text: 'Apply CPAP',
      detail: 'Ensure adequate oxygen supply. Coach to reduce anxiety. Upright position; pulse oximetry, capnography, ECG as available. Mask on, secure until minimal leak. If device allows, titrate O2 to SpO2 94 - 98%. Consider nasal cannula under the mask. Asthma/COPD: continue nebulizers. No commercial device: BVM with PEEP valve (5 - 15 cmH2O), nasal cannula 15 lpm, O2 to BVM at least 15 lpm, continuous mask seal, do not compress the BVM. Use cautiously if unable to follow commands or agitated/combative.',
      dose: 'Adjust Positive End Expiratory Pressure (PEEP) to 5 - 15 cmH2O to effect for patient condition (5.4). Asthma/COPD: up to a maximum of 10 - 15 cm H2O pressure support (2.3A). CHF: maximum 15 cmH2O pressure support (3.3).',
      cite: '5.4, PDF p. 119',
      level: 'EMT',
      critical: true,
      report: 'CPAP applied',
      next: 'cpapAnx',
    },
    cpapAnx: {
      type: 'action',
      text: 'Consider anxiolytic for CPAP',
      detail: 'For IN midazolam use a 5 mg/mL concentration. Give cautiously in frail or debilitated patients; consider lower doses.',
      dose: 'Midazolam 2.5 mg IV, may repeat once in 5 minutes, OR *Midazolam 5 mg IM/IN, may repeat once in 5 minutes, OR Lorazepam 1 mg IV, may repeat once in 5 minutes, OR Diazepam 5 mg IV, may repeat once in 5 minutes OR Ketamine: 10 - 20 mg IV diluted in 50 - 100 mL 0.9% NaCl or D5W over 10 minutes (no IV pump needed) may repeat every 5 minutes to a total of 40 mg, as tolerated, OR 25 - 50 mg IM may repeat every 30 minutes, as tolerated',
      cite: '5.4, PDF p. 120',
      level: 'Paramedic',
      report: 'Anxiolytic for CPAP',
      next: 'cpapOngoing',
    },
    cpapOngoing: {
      type: 'action',
      text: 'Maintain CPAP for transport; notify hospital',
      detail: 'If the patient stabilizes, keep CPAP on for the whole transport and tell the receiving hospital to prepare for a CPAP patient. If the patient deteriorates, stop CPAP and assist breathing by BVM with PEEP valve. Document CPAP time, provider, and serial SpO2 and capnography.',
      cite: '5.4, PDF p. 119',
      level: 'EMT',
      critical: true,
      report: 'CPAP maintained; hospital notified of CPAP patient',
      next: 'END',
    },
  },
};
