// NH Patient Care Protocols v9.3, 2.24 Stroke - Adult (Northern New England Unified Guideline), PDF pp. 74-76.
// NH has no separate pediatric stroke protocol (TOC lists 2.24 as "Adult & Pediatric"; the page header says "Stroke - Adult").
export default {
  id: 'stroke',
  title: 'Stroke / TIA',
  category: 'Medical',
  nh: '9.3',
  verified: false,
  source: { doc: 'NH Patient Care Protocols v9.3', section: '2.24', page: 'PDF p. 74' },
  keywords: ['stroke', 'cva', 'tia', 'weakness', 'facial droop', 'slurred speech', 'befast'],
  start: 'suspect',
  nodes: {
    suspect: {
      type: 'question',
      text: 'Any NEW or SUDDEN stroke symptoms?',
      help: 'NH "Suspect stroke": one-sided weakness or paralysis of face, limb or side of body (including facial droop); one-sided numbness; dizziness/vertigo; sudden vision problem (loss of vision in one eye or one side of vision); trouble with balance, uncoordinated limb, gait disturbance; trouble speaking or understanding (slurred or wrong words); severe headache for no obvious reason; altered mental state.',
      cite: '2.24, PDF p. 74',
      answers: [
        { label: 'Yes', finding: 'New/sudden neurologic symptoms', suggest: ['Stroke'], next: 'rpc' },
        { label: 'No', next: 'END' },
      ],
    },
    rpc: {
      type: 'action',
      text: 'Routine Patient Care',
      detail: 'NH Routine Patient Care (1.0).',
      level: 'EMT',
      cite: '2.24, PDF p. 74',
      report: 'Routine patient care',
      next: 'lkw',
    },
    lkw: {
      type: 'question',
      text: 'Time Last Known Well (TLKW)',
      ask: 'When was the last time they were completely normal? Record the exact clock time.',
      help: 'TLKW is the last time the patient was known to be at their neurological baseline. If they woke with symptoms, it is when they were last known at baseline. Ask if they got up during the night and were at baseline.',
      cite: '2.24, PDF p. 74 and p. 76',
      answers: [
        { label: 'Less than 4.5 hours', finding: 'TLKW less than 4.5 hours', redFlag: 'Stroke: TLKW < 4.5 h', next: 'witness' },
        { label: '4.5 to 24 hours', finding: 'TLKW 4.5 to 24 hours', redFlag: 'Stroke: TLKW 4.5-24 h', next: 'witness' },
        { label: 'More than 24 hours', finding: 'TLKW more than 24 hours', next: 'witness' },
        { label: 'Cannot determine', finding: 'TLKW could not be determined', next: 'witness' },
      ],
    },
    witness: {
      type: 'action',
      text: 'Bring the witness, or get the witness best contact number',
      detail: 'Transport the witness, family or caregiver, or get the witness best phone number so hospital staff can verify symptom onset / TLKW.',
      level: 'EMT',
      cite: '2.24, PDF p. 74 and p. 76',
      report: 'Witness transported or callback number obtained',
      next: 'face',
    },
    face: {
      type: 'question',
      text: 'Prehospital Stroke Screen: Facial Droop',
      ask: 'Smile and show me your teeth.',
      help: 'Normal: both sides of the face move equally well. Abnormal: one side of the face does not move as well as the other.',
      cite: '2.24, PDF p. 74',
      answers: [
        { label: 'Normal', next: 'arm' },
        { label: 'Abnormal', finding: 'Facial droop', suggest: ['Stroke'], next: 'arm' },
      ],
    },
    arm: {
      type: 'question',
      text: 'Prehospital Stroke Screen: Arm Drift',
      ask: 'Close your eyes and hold your arms out for 10 seconds.',
      help: 'Normal: both arms move the same, or both arms do not move at all. Abnormal: one arm does not move, or one arm drifts down compared to the other.',
      cite: '2.24, PDF p. 74',
      answers: [
        { label: 'Normal', next: 'speech' },
        { label: 'Abnormal', finding: 'Arm drift', suggest: ['Stroke'], next: 'speech' },
      ],
    },
    speech: {
      type: 'question',
      text: 'Prehospital Stroke Screen: Speech',
      ask: 'Repeat after me: "You can\'t teach an old dog new tricks."',
      help: 'Normal: says the correct words without slurring. Abnormal: slurs words, says the wrong word, or is unable to speak.',
      cite: '2.24, PDF p. 74',
      answers: [
        { label: 'Normal', next: 'screen' },
        { label: 'Abnormal', finding: 'Abnormal speech', suggest: ['Stroke'], next: 'screen' },
      ],
    },
    screen: {
      type: 'question',
      text: 'Was ANY of facial droop, arm drift, or speech abnormal?',
      help: 'NH: the stroke screen is positive if any abnormal finding in facial droop, arm drift or speech.',
      cite: '2.24, PDF p. 74',
      answers: [
        { label: 'Yes: screen POSITIVE', finding: 'Prehospital stroke screen positive', suggest: ['Stroke'], redFlag: 'Positive prehospital stroke screen', next: 'fasted' },
        { label: 'No: screen negative', finding: 'Prehospital stroke screen negative', next: 'pcs' },
      ],
    },
    fasted: {
      type: 'info',
      text: 'Screen positive: score FAST-ED (probability of large vessel occlusion)',
      items: [
        'Facial palsy (smile): none or minor = 0; partial or complete paralysis of one side = 1',
        'Arm weakness (arms out, palms up, 10 sec): no drift or both arms slowly move down equally = 0; drift or some effort against gravity = 1; no effort against gravity or no movement in one or both arms = 2',
        'Speech change (name 3 common items; "show me 2 fingers"): names at least 2 of 3 and follows command = 0; names none or only 1 = 1; unable to show two fingers to command = 1',
        'Time: when was the patient last known well?',
        'Eye deviation: looks to both sides without difficulty = 0; moves eyes both directions but with clear difficulty = 1; gaze fixed to one side = 2',
        'Denial/neglect (only if arm weakness AND commands followed): recognizes weakness and own arm = 0; does not recognize weakness when asked "Are you weak anywhere?" = 1; does not recognize own arm when asked "Whose arm is this?" = 1',
      ],
      cite: '2.24, PDF p. 75',
      next: 'fastedScore',
    },
    fastedScore: {
      type: 'question',
      text: 'FAST-ED total',
      cite: '2.24, PDF p. 75-76',
      answers: [
        { label: '4 or more (positive LVO screen)', finding: 'FAST-ED 4 or more: possible LVO', redFlag: 'Possible LVO (FAST-ED >= 4)', next: 'glucose' },
        { label: 'Less than 4 (negative LVO screen)', finding: 'FAST-ED less than 4', next: 'glucose' },
      ],
    },
    pcs: {
      type: 'info',
      text: 'Negative screen but still worried? Think posterior circulation stroke',
      items: [
        'Posterior circulation stroke is usually missed by common screens (e.g., CPSS, FAST-ED).',
        'Look for sudden vision problems, sudden balance/coordination changes, sudden dizziness, or nausea and vomiting.',
        'Contact Medical Direction if the initial screens are negative but your judgement and the presentation are still concerning for stroke.',
        'Consider stroke mimics: migraine, hypoglycemia, seizures, intoxication, sepsis, cerebral infection, toxic ingestion, neuropathies (Bell\'s palsy), neoplasms, hypertensive encephalopathy.',
      ],
      cite: '2.24, PDF p. 76',
      next: 'glucose',
    },
    glucose: {
      type: 'action',
      text: 'Check blood glucose',
      detail: 'Blood glucose is part of the NH Prehospital Stroke Screening Tool and the first Stroke Alert criterion. Enter the value in Vitals.',
      level: 'EMT',
      critical: true,
      cite: '2.24, PDF p. 74-75',
      report: 'Blood glucose checked',
      next: 'glucoseLow',
    },
    glucoseLow: {
      type: 'question',
      text: 'Glucose below 60 mg/dL?',
      cite: '2.24, PDF p. 74',
      answers: [
        { label: 'Yes, below 60', finding: 'Glucose below 60 mg/dL', suggest: ['Hypoglycemia'], redFlag: 'Glucose < 60 mg/dL: correct, then re-screen', next: 'correct' },
        { label: 'No, 60 or above', next: 'checklist' },
      ],
    },
    correct: {
      type: 'action',
      text: 'Correct glucose (run the Diabetic / Hypoglycemia protocol), then repeat the stroke screen',
      detail: 'NH: "Correct glucose if < 60 mg/dL." Stroke Alert needs glucose that is, or has been corrected to, greater than 60 mg/dL.',
      verify: 'NH book conflict: 2.24 says "See Hypoglycemia Protocol 2.10A or 2.10P", but the Table of Contents numbers Hypoglycemia as 2.11A / 2.11P (2.10 is Hyperthermia). This app links to 2.11A.',
      level: 'EMT',
      critical: true,
      cite: '2.24, PDF p. 74',
      report: 'Hypoglycemia corrected per protocol',
      next: 'checklist',
    },
    checklist: {
      type: 'info',
      text: 'Thrombolytic checklist (try to complete): has the patient had any of these?',
      items: [
        '1. Severe head trauma or intracranial or spinal surgery within the past 3 months?',
        '2. Major non-cranial surgery or trauma within 14 days with uncontrolled bleeding (e.g., internal organs)?',
        '3. Spontaneous (non-traumatic) intracranial hemorrhage at any time in the past?',
        '4. Taking any anticoagulants ("blood thinners"), oral or injectable? If yes, when was the last dose? (warfarin/Coumadin/Jantoven, heparin incl. Lovenox, dabigatran/Pradaxa, rivaroxaban/Xarelto, apixaban/Eliquis, betrixaban/Bevyxxa, edoxaban/Savaysa). Tell hospital staff right away.',
      ],
      cite: '2.24, PDF p. 76',
      next: 'alertCriteria',
    },
    alertCriteria: {
      type: 'question',
      text: 'Stroke Alert Criteria: is the answer YES to all three?',
      help: '1) Blood glucose is, or has been corrected to, greater than 60 mg/dL. 2) Deficit unlikely due to head trauma or other identifiable causes. 3) Positive Prehospital Stroke Screen AND time last known well less than 4.5 hours, OR FAST-ED 4 or more AND time last known well less than 24 hours.',
      cite: '2.24, PDF p. 75',
      answers: [
        { label: 'Yes to all', finding: 'Meets NH Stroke Alert criteria', redFlag: 'STROKE ALERT', next: 'notify' },
        { label: 'No', finding: 'Does not meet NH Stroke Alert criteria', next: 'oxygen' },
      ],
    },
    notify: {
      type: 'action',
      text: 'Call STROKE ALERT to the receiving hospital',
      detail: 'Report: time last known well, findings from the screening tools (FAST-ED score), and thrombolytic checklist results.',
      level: 'EMT',
      critical: true,
      cite: '2.24, PDF p. 74-75',
      report: 'Stroke Alert called to receiving hospital',
      next: 'oxygen',
    },
    oxygen: {
      type: 'action',
      text: 'Oxygen to keep SpO2 94% - 98%',
      detail: 'For symptomatic patients.',
      dose: 'Administer oxygen to maintain SPO2 between 94% - 98%',
      level: 'EMT',
      cite: '2.24, PDF p. 74',
      report: 'O2 titrated to SpO2 94-98%',
      next: 'head',
    },
    head: {
      type: 'action',
      text: 'Head of stretcher up 30 degrees',
      detail: 'Unless the patient requires spinal motion restriction.',
      level: 'EMT',
      cite: '2.24, PDF p. 74',
      report: 'Head of stretcher elevated 30 degrees',
      next: 'scene',
    },
    scene: {
      type: 'action',
      text: 'Minimize on-scene time. Do not delay for ALS intercept.',
      level: 'EMT',
      critical: true,
      cite: '2.24, PDF p. 74',
      report: 'Minimal scene time',
      next: 'ecg',
    },
    ecg: {
      type: 'action',
      text: 'Acquire and transmit 12-lead ECG, if available',
      level: 'EMT',
      cite: '2.24, PDF p. 74',
      report: '12-lead acquired and transmitted',
      next: 'iv',
    },
    iv: {
      type: 'action',
      text: 'IV (18 gauge, right AC preferred) and 250 mL IV fluid',
      dose: 'Establish IV (18 gauge catheter & right AC preferred site) and administer 250 mL IV fluid.',
      level: 'AEMT',
      cite: '2.24, PDF p. 74',
      report: 'IV 18g R AC, 250 mL IV fluid',
      next: 'destination',
    },
    destination: {
      type: 'question',
      text: 'Destination: positive LVO screen (FAST-ED 4 or more) AND TLKW more than 4.5 and less than 24 hours?',
      help: 'NH Destination Guidance for Possible LVO Stroke Patients. Use your local stroke plan.',
      cite: '2.24, PDF p. 76',
      answers: [
        { label: 'Yes', finding: 'Possible LVO, TLKW 4.5-24 h', next: 'endovascular' },
        { label: 'No (negative LVO screen, or TLKW < 4.5 h or > 24 h)', next: 'nearest' },
      ],
    },
    endovascular: {
      type: 'action',
      text: 'If feasible, rapid transport to an Endovascular Center, per your local stroke plan',
      verify: 'Local policy: NH leaves the endovascular center choice and feasibility to the service\'s local stroke plan (PDF p. 77 is a blank page for it).',
      level: 'EMT',
      critical: true,
      cite: '2.24, PDF p. 74 and p. 76',
      report: 'Rapid transport to endovascular center',
      next: 'END',
    },
    nearest: {
      type: 'action',
      text: 'Rapid transport to the Nearest Appropriate Hospital',
      detail: 'Includes an Endovascular Center if that is the closest hospital.',
      verify: 'Local policy: NH says to use your local stroke plan for destination (PDF p. 77 is a blank page for it).',
      level: 'EMT',
      critical: true,
      cite: '2.24, PDF p. 74 and p. 76',
      report: 'Rapid transport to nearest appropriate hospital',
      next: 'END',
    },
  },
};
