/* Legend of JRMA: call content.
 *
 * Every medical fact here is listed with its source and review status in
 * docs/reference/call-content.md. Change one, change both.
 *
 * Call fields:
 *   tier     0 = EMT, 1 = AEMT, 2 = Paramedic (sets hearts and hint cost)
 *   npc      id of the overworld character who starts the call
 *   steps    correct actions. `g` is the priority group: steps in the lowest
 *            unfinished group are correct now; later groups are "right move,
 *            wrong time". Steps sharing a group can be done in any order.
 *   wrong    distractors. sev 1 or 2 costs patient hearts; sev 0 is a joke.
 *   meh      acceptable but not best; costs time, no hearts.
 *   nh       NH Patient Care Protocols topics to verify this call against.
 */
window.JRMA = window.JRMA || {};

/* Three levels. Each: a few monster calls within that license's scope, then a
   boss call, then the boss's phase 2 (a protocol trial) that advances the
   license. */
window.JRMA.LEVELS = [
  { license: 'EMT', monsters: ['bleed', 'od', 'hypo', 'ana', 'psych'], boss: 'arrest', trial: 'trial-emt' },
  { license: 'AEMT', monsters: ['hypo2', 'asthma'], boss: 'rollover', trial: 'trial-aemt' },
  { license: 'Paramedic', monsters: ['stemi', 'brady'], boss: 'arrest2', trial: 'trial-medic' },
];
window.JRMA.ORDER = window.JRMA.LEVELS.flatMap((l) => [...l.monsters, l.boss, l.trial]);

window.JRMA.CALLS = [
  /* ---------------- EMT level (boss: arrest) ---------------- */
  {
    id: 'bleed', tier: 0, npc: 'gary', loc: 'Gary\'s woodlot, below Mount Monadnock', dir: 'northwest',
    title: 'Chainsaw vs. Leg', domain: 'Trauma: bleeding control',
    dispatch: 'Medic 1, respond Priority 1 to a woodlot below Mount Monadnock for a 45-year-old male, chainsaw versus leg. Caller states, quote, "there\'s a LOT of it."',
    scene: 'Gary, 45, a self-described chainsaw enthusiast, is sitting on a stump. Bright red blood spurts from his left thigh in time with his pulse. The chainsaw is still running. Gary is narrating all of this to his livestream.',
    urgent: 'So it turns out the chainsaw was on. HEY CHAT, THE EMTs ARE HERE.',
    after: 'One point two million views! Also, thanks for my leg.',
    monster: { cond: 'Arterial Hemorrhage', name: 'The Bleedinator', draw: 'bleed', hit: 'sputters', win: 'dries up and blows away' },
    patient: { look: 'gary', pose: 'sit' },
    vitals: { Mental: 'Alert, yelling', HR: '128/min', BP: '92/58', RR: '24/min', SpO2: '96%', Skin: 'Pale, cool, sweaty' },
    steps: [
      { g: 0, label: 'Shut off the chainsaw, gloves on', hint: 'Before you touch Gary, what here can hurt YOU?',
        why: 'Scene safety first. A running chainsaw is a hazard with teeth, and his blood is a hazard without them. A rescuer who gets hurt becomes patient number two.' },
      { g: 1, label: 'Tourniquet on bare skin, 2-3 in above the wound', hint: 'What is leaving his body fastest, and what stops it?',
        mini: { type: 'mash', need: 14, secs: 5 },
        why: 'Spurting bright red blood from a limb is life-threatening, and pressure on a chainsaw wound is impractical. NH: on bare skin, 2-3 inches above the bleeding site, never over a joint. Tighten until the bleeding stops. Still bleeding? Add a second one right next to it. It will hurt. That is how you know it works.',
        early: 'Right tool, but the chainsaw is still running next to your face. Make the scene safe first.',
        vitals: { HR: '122/min', Skin: 'Pale, cool. Bleeding controlled' } },
      { g: 2, label: 'Write the time on the tourniquet', hint: 'The surgeon is going to ask one question about that tourniquet.',
        why: 'NH: document the time of tourniquet application. Surgeons need to know how long the limb has gone without blood flow. "Sometime after lunch" is not a time.',
        early: 'Writing the time before the tourniquet is on is just journaling.' },
      { g: 2, label: 'Check airway and breathing', hint: 'The bleeding is controlled. Now what?',
        why: 'Massive bleeding first, then airway and breathing. Gary is yelling at his livestream, so his airway is open. Breathing is fast (24/min) but adequate.',
        early: 'Airway matters, but he is talking and his blood is leaving at speed. Stop the bleeding first.' },
      { g: 3, label: 'Blanket on, lay him flat (treat for shock)', hint: 'Cold blood does not clot well.',
        why: 'NH 4.6: keep him supine and warm, and prevent heat loss. Cold blood clots poorly; hypothermia, acidosis, and poor clotting feed each other. Blankets are medicine.',
        early: 'Warmth matters, but a blanket will not stop a spurting artery. Fix the bleeding first.',
        vitals: { BP: '98/62', Skin: 'Pale, warming up' } },
      { g: 4, label: 'Rapid transport to a Level 1 or 2 trauma center', hint: 'You stopped the leak. Who fixes the pipe?',
        why: 'NH: a patient who needed a tourniquet meets high-risk trauma criteria and goes to a Level 1 or 2 trauma center. Keep scene time short.',
        early: 'Load and go is right, but not with an open artery. Control the bleeding before you move him.' },
    ],
    wrong: [
      { sev: 1, label: 'Loosen the tourniquet every 10 min so the leg can "breathe"', why: 'Old myth. Loosening restarts the bleeding and spends blood he does not have. Leave it on for the hospital.' },
      { sev: 1, label: 'Take a full set of vitals before touching the bleed', why: 'NH: do not wait for signs of shock to apply a tourniquet. Treat the life threat you can see.' },
      { sev: 1, label: 'Elevate the leg and wait', why: 'Elevation does not control arterial bleeding. It wastes time while he bleeds.' },
      { sev: 1, label: 'Press on a pressure point in the groin', why: 'Pressure points are not in the NH hemorrhage protocol. Use direct pressure, a tourniquet, or packing.' },
      { sev: 1, label: 'Apply a Band-Aid', why: 'The Band-Aid has been defeated. It never stood a chance.' },
      { sev: 0, label: "Like and subscribe to Gary's livestream", why: "Gary's 14 viewers cannot stop arterial bleeding. {partner} sighs into an iced coffee." },
    ],
    meh: [
      { label: 'Direct pressure with gauze', why: 'Good instinct. NH starts with direct pressure, but a spurting chainsaw wound in the thigh makes pressure impractical. Hold it while the tourniquet comes out of the bag.' },
    ],
    numbers: ['Massive bleeding first, then airway and breathing', 'Tourniquet: bare skin, 2-3 in above the wound, never over a joint', 'Still bleeding? Second tourniquet side by side', 'Write the time; never loosen it to let the limb "breathe"'],
    nh: ['Hemorrhage Control (4.4)', 'Shock - Traumatic (4.6)', 'Routine Patient Care (1.0)', 'Trauma Triage and Transport Decision (8.17)'],
    outro: 'Gary keeps the leg. He has already posted about it.',
  },
  {
    id: 'od', tier: 0, npc: 'clerk', loc: 'Gas-n-Go, Route 202 north', dir: 'north',
    title: 'Unresponsive in the Restroom', domain: 'Airway, ventilation, overdose',
    dispatch: 'Medic 1, Priority 1, Gas-n-Go on Route 202 for an unresponsive male in the restroom. Clerk states he has been in there since the Patriots pregame.',
    scene: 'A man about 30 lies on the restroom floor. He snores, stops, then snores again. His lips are blue and his pupils are pinpoint. A used syringe sits right where your knee is about to go.',
    urgent: 'He is in the restroom! He stopped snoring a minute ago. That is bad, right?',
    after: 'He left a thank-you note on the slushie machine.',
    monster: { cond: 'Opioid Overdose', name: 'The Opioid Lich', draw: 'lich', hit: 'loses its grip', win: 'lets go of his lungs and fades away' },
    patient: { look: 'od', pose: 'lie' },
    vitals: { Mental: 'Unresponsive to pain', HR: '54/min', BP: '100/64', RR: '4/min, shallow', SpO2: '78%', Skin: 'Blue lips, cool' },
    steps: [
      { g: 0, label: 'PPE on, move the syringe into a sharps container', hint: 'Look at the floor near your knee.',
        why: 'Needlesticks spread hepatitis and HIV. Clear the sharps before you kneel. Then your full attention goes to him.' },
      { g: 1, label: 'Check responsiveness, breathing, and pulse (10 sec max)', hint: 'Before choosing a treatment: pulse? breathing?',
        why: 'Carotid pulse present, but only 4 shallow breaths a minute. This is respiratory arrest with a pulse. He needs you to breathe for him.',
        early: 'You cannot choose a treatment until you know if he has a pulse and is breathing.' },
      { g: 2, label: 'Open the airway: head-tilt chin-lift + OPA or NPA', hint: 'Snoring is a sound the tongue makes.',
        why: 'Snoring means the tongue is blocking the airway. Open it, then hold it open with an adjunct. NH lets you use an NPA with an OPA. No gag reflex, so an OPA is tolerated.',
        early: 'Airway is right, but check pulse and breathing first so you know which path you are on.' },
      { g: 3, label: 'BVM with oxygen: 10-12 breaths a minute', hint: 'At 4 breaths a minute, who is doing the breathing?',
        why: 'NH: if breathing is ineffective, ventilate with 100% oxygen by BVM, 10-12 breaths a minute. Each breath just enough to see the chest rise. Over-bagging fills the stomach and invites vomit.',
        early: 'Bagging through a closed airway just inflates his stomach. Open the airway first.',
        vitals: { HR: '72/min', SpO2: '94%', Skin: 'Pinking up' } },
      { g: 4, label: 'Naloxone IN: 2 mg (1 mg each nostril) or 4 mg spray', hint: 'Oxygen is going in. Now reverse the cause.',
        why: 'NH: naloxone 1 mg per nostril (2 mg total) or a 4 mg nasal spray, titrated until breathing recovers, not until he is fully awake. Bag first: naloxone takes minutes and his brain needs oxygen now.',
        early: 'Naloxone is right, but it is not first. It takes minutes to work and his brain needs oxygen now. Ventilate first.',
        vitals: { Mental: 'Groggy, opens eyes', HR: '88/min', RR: '14/min', SpO2: '97%' } },
      { g: 5, label: 'Reassess: suction ready, expect vomiting or agitation', hint: 'What happens when an opioid is reversed fast?',
        why: 'NH warns patients may become agitated or violent after naloxone. Vomiting and withdrawal are common. Keep suction close and your voice calm.',
        early: 'Reassessment is always right, but he is not breathing enough yet. Fix that first.' },
      { g: 5, label: 'Transport and monitor: naloxone can wear off first', hint: 'Which lasts longer, the naloxone or the opioid?',
        why: 'NH: naloxone may wear off within an hour, and some opioids last longer. He can stop breathing again. Refusal after a treated overdose is high-risk in NH. Offer resources, not judgment.',
        early: 'Transport is coming, but he cannot breathe on his own yet. Fix that first.' },
    ],
    wrong: [
      { sev: 1, label: 'Put ice down his pants', why: 'Street myth. It does nothing except make you the weirdest person in a gas station restroom, which is a high bar.' },
      { sev: 1, label: 'Sternal rub for 5 minutes', why: 'A quick painful stimulus checks responsiveness. Five minutes of it just delays breathing for him.' },
      { sev: 1, label: 'Start chest compressions', why: 'He has a pulse. He needs ventilation, not compressions.' },
      { sev: 1, label: 'Nasal cannula at 2 L/min', why: 'A cannula only helps someone who is breathing. NH: ineffective breathing gets a BVM with 100% oxygen.' },
      { sev: 0, label: 'Lecture him about his life choices', why: 'Stigma keeps people from calling 911. Treat the patient, offer resources, skip the TED talk.' },
    ],
    numbers: ['Ineffective breathing: BVM with 100% O2, 10-12 breaths/min', 'Naloxone IN: 1 mg each nostril (2 mg) or 4 mg spray', 'Titrate naloxone to breathing, not to full wakefulness', 'Naloxone can wear off within an hour'],
    nh: ['Opioid Overdose - Adult (2.17A)', 'Airway Management Protocol - Adult (5.1A)', 'Routine Patient Care (1.0)', 'Refusal of Care (8.14)'],
    outro: 'He is breathing on his own and took a recovery resource card. That is a win.',
  },
  {
    id: 'hypo', tier: 0, npc: 'kevin', loc: 'Cubicle Keep, downtown Jaffrey', dir: 'northeast',
    title: 'Acting Drunk at the Potluck', domain: 'Medical: diabetic emergency',
    dispatch: 'Medic 1, Priority 2, Cubicle Keep, downtown Jaffrey, third floor, for a 52-year-old female acting intoxicated at the office potluck. Caller states she has not been drinking. Probably.',
    scene: 'Deb from Accounting is sweaty, pale, and slurring threats at the copier. A coworker says she takes insulin and skipped lunch to finish the quarterly reports.',
    urgent: 'Deb is fighting the copier and the copier is winning! Third floor!',
    after: 'Deb says thanks. She also says nobody mentions the copier. Ever.',
    monster: { cond: 'Hypoglycemia', name: 'The Sugar Crash Goblin', draw: 'goblin', hit: 'drops a sprinkle', win: 'crumbles like a stale donut' },
    patient: { look: 'deb', pose: 'stand' },
    vitals: { Mental: 'Confused, fighting the copier', HR: '112/min', BP: '138/84', RR: '18/min', SpO2: '98%', Skin: 'Pale, cool, drenched in sweat', BGL: 'Not checked' },
    steps: [
      { g: 0, label: 'PPE on, move the crockpot out of swinging range', hint: 'Confused people swing. Hot things burn.',
        why: 'Confused patients swing. Hot crockpots burn. Make space before you get close.' },
      { g: 1, label: 'Primary assessment: airway, breathing, circulation', hint: 'Before chasing the cause, rule out the immediate killers.',
        why: 'She is talking (loudly), so the airway is open. Breathing and pulse are adequate. No immediate killers, so you have time to find the cause.',
        early: 'Primary assessment comes right after scene safety. Get there.' },
      { g: 2, label: 'Check blood glucose', hint: 'Altered + diabetic. What number do you need?',
        why: 'Altered mental status plus diabetes means check the sugar. Honestly, altered mental status plus anything means check the sugar. Result: 38 mg/dL. NH defines a hypoglycemic emergency as under 60 with altered mental status.',
        early: 'Checking sugar is right, but do the primary first. Airway problems kill faster than low sugar.',
        vitals: { BGL: '38 mg/dL' } },
      { g: 3, label: 'Confirm she can swallow and protect her airway', hint: 'Oral glucose only works if it goes down the right pipe.',
        why: 'NH: oral glucose only if she is alert enough to swallow and protect her airway. If she cannot, EMTs give intranasal glucagon or a glucagon auto-injector, if carried.',
        early: 'Good question, but confirm her sugar is low before planning the fix.' },
      { g: 4, label: 'Oral glucose gel, 15-30 g', hint: 'Low sugar, can swallow. Treat it.',
        why: 'NH: 15 to 30 grams of glucose gel or equivalent, a little at a time. Juice or regular soda counts as an equivalent.',
        early: 'Probably the right fix, but you have not proven the sugar is low or that she can swallow. Thirty seconds of checking prevents a wrong answer.',
        vitals: { Mental: 'Improving' } },
      { g: 5, label: 'Recheck sugar and mental status', hint: 'Did it work?',
        why: 'Always recheck after treating. BGL is now 92 mg/dL. Deb apologizes to the copier.',
        early: 'Rechecking is right, but you have not treated anything yet.',
        vitals: { Mental: 'Alert, embarrassed', HR: '88/min', Skin: 'Warm, dry', BGL: '92 mg/dL' } },
      { g: 6, label: 'Push for transport; a refusal here is high-risk', hint: 'Oral glucose is a spike, not a fix.',
        why: 'Insulin and some diabetes pills can drop her again. NH lists refusing after a treated low sugar as a high-risk refusal. If she still refuses with capacity, get about 15 g of complex carbs and 12-15 g of protein into her first.',
        early: 'Disposition comes last. Make sure the treatment worked first.' },
    ],
    wrong: [
      { sev: 2, label: "Give her insulin, she's diabetic", why: 'NO. Insulin lowers blood sugar, and hers is already in the basement. This mistake kills people. It is in no NH EMS standing order.' },
      { sev: 1, label: 'Assume she is drunk and call the police', why: 'Low blood sugar looks like intoxication: confusion, slurring, stumbling. Assuming "drunk" is how diabetic emergencies get missed.' },
      { sev: 1, label: 'Let her sleep it off at her desk', why: 'Sleeping it off is how a low sugar becomes a seizure or a coma.' },
      { sev: 0, label: 'Try a potluck meatball', why: 'They are excellent meatballs. They are not a treatment. {partner} takes two anyway.' },
    ],
    numbers: ['NH hypoglycemic emergency: under 60 mg/dL with altered mental status', 'Oral glucose: 15-30 g, only if she can swallow and protect her airway', 'Cannot swallow? EMTs give IN glucagon or a glucagon auto-injector', 'Refusal after a treated low: high-risk. Carbs and protein if she refuses.'],
    nh: ['Hypoglycemia - Adult (2.11A)', 'Refusal of Care (8.14)'],
    outro: 'Deb finished the reports. Then she finished the meatballs.',
  },
  {
    id: 'ana', tier: 0, npc: 'todd', loc: 'Craft fair on the Jaffrey Center Common', dir: 'west',
    title: 'Bee Beard Gone Wrong', domain: 'Medical: anaphylaxis',
    dispatch: 'Medic 1, Priority 1, the craft fair on the Common in Jaffrey Center, for a 34-year-old male stung multiple times during the bee beard contest. Difficulty breathing.',
    scene: 'Todd, 34, entered the bee beard contest despite being "a little allergic." Hives everywhere, swollen lips, a hoarse voice, loud wheezing. His own epinephrine auto-injector is in his fanny pack. The bees are still very much present.',
    urgent: '(wheezing) The bees... were supposed to be... friendly...',
    after: 'Banned for life. Worth it. Also, thank you. Mostly for the epi.',
    monster: { cond: 'Anaphylaxis', name: 'Anaphyl-Axe, the Bee Knight', draw: 'bee', hit: 'drops its axe', win: 'buzzes off in disgrace' },
    patient: { look: 'todd', pose: 'sit' },
    vitals: { Mental: 'Anxious, hoarse', HR: '128/min', BP: '78/44', RR: '30/min, wheezing', SpO2: '89%', Skin: 'Flushed, hives, swollen lips' },
    steps: [
      { g: 0, label: 'Move Todd away from the bees, PPE on', hint: 'What is still stinging him?',
        why: 'More stings mean more venom. Get out of the swarm. Scrape stingers off fast with anything; speed beats technique.' },
      { g: 1, label: 'Recognize anaphylaxis: skin + airway + low BP', hint: 'Hives alone is an allergy. What else is happening?',
        why: 'NH: a likely allergen exposure plus two or more body systems involved. Hives, airway swelling, wheezing, and a BP of 78/44: anaphylaxis with shock. Time-critical.',
        early: 'Name the problem after the scene is safe. Bees first.' },
      { g: 2, label: 'Epinephrine auto-injector 0.3 mg IM, outer thigh', hint: 'One drug is first-line for anaphylaxis.',
        why: 'Epinephrine first, and do not delay it for second-line drugs like diphenhydramine. NH: adult auto-injector 0.3 mg IM, outer thigh, through clothing if needed.',
        early: 'Epi is the right call, but you skipped a step. Make the scene safe and confirm it is anaphylaxis first.',
        vitals: { HR: '118/min', BP: '96/60', RR: '26/min, less wheezing', SpO2: '92%' } },
      { g: 3, label: 'High-flow O2: non-rebreather, at least 8 L/min up to flush', hint: 'SpO2 89% and wheezing.',
        why: 'SpO2 89% and wheezing. NH runs a non-rebreather at 8 L/min or more, up to flush rate.',
        early: 'Oxygen helps, but it will not open a swelling airway or raise his pressure. Epi first.',
        vitals: { SpO2: '96%' } },
      { g: 3, label: 'Lay him flat, legs raised (sit up only if breathing demands it)', hint: 'BP 78/44. Should he stand?',
        why: 'Low blood pressure: flat with legs raised. Sitting or standing up during anaphylactic shock has been linked to sudden cardiac arrest. If breathing is the bigger problem, semi-sitting is the compromise.',
        early: 'Positioning matters, but it will not reverse anaphylaxis. Epi first.' },
      { g: 4, label: 'Reassess in 5 min; repeat epi once if no better', hint: 'One dose is not always enough.',
        why: 'NH: if signs and symptoms do not resolve, EMTs may repeat epinephrine in 5 minutes. More doses than that: contact Medical Control.',
        early: 'Reassess after you have treated something.',
        vitals: { Mental: 'Calmer, voice clearer', BP: '108/70', RR: '20/min', Skin: 'Hives fading' } },
      { g: 5, label: 'Transport: reactions can return hours later', hint: 'He feels better. Does that mean he stays?',
        why: 'Symptoms can return hours later (a biphasic reaction), even after he feels fine. Everyone who needs epi gets evaluated at a hospital.',
        early: 'Transport is coming, but treat the airway and blood pressure first.' },
    ],
    wrong: [
      { sev: 1, label: 'Give an antihistamine and wait 30 minutes', why: 'NH: do not delay epinephrine for second-line medications such as diphenhydramine. Antihistamines do not fix airway swelling or blood pressure.' },
      { sev: 1, label: 'Inject the epi into his thumb', why: 'Epinephrine injected into a finger can cut off that finger\'s blood flow. Target: the outer thigh.' },
      { sev: 1, label: 'Have him walk to the ambulance', why: 'Standing up in anaphylactic shock can crash his blood pressure. Carry him.' },
      { sev: 1, label: 'Remove every stinger with tweezers, one by one', why: 'Ten minutes of tweezer craftwork while his airway closes is a bad trade. Scrape them off fast, then treat.' },
      { sev: 0, label: 'Ask the bees to leave politely', why: 'The bees have unionized. They are not leaving.' },
    ],
    numbers: ['Adult epi auto-injector: 0.3 mg IM, outer thigh', 'Under 25 kg: 0.15 mg (EpiPen Jr). 25 kg and up: 0.3 mg', 'Repeat once in 5 min if no better, then call Medical Control', 'Never delay epi for diphenhydramine'],
    nh: ['Allergic Reaction/Anaphylaxis - Adult (2.2A)', 'Allergic Reaction/Anaphylaxis - Pediatric (2.2P)', 'Airway Management Procedure (5.0)'],
    outro: 'Todd has been banned from the bee beard contest for life. He calls it a personal best.',
  },
  {
    id: 'psych', tier: 0, npc: 'reyes', loc: 'Pine Hollow Apartments, east side (staging lot)', dir: 'far east',
    title: 'Stage for PD', domain: 'Special: behavioral emergency, scene safety',
    dispatch: 'Medic 1, Priority 1, Pine Hollow Apartments, unit 2B, for a 28-year-old male threatening self-harm with a knife. PD is en route. Stage until PD advises the scene is secure.',
    scene: 'You roll up to the staging lot around the corner, out of sight of the building. Sgt. Reyes: "Two units going in. Stay here until I say the scene is secure." {partner} unwraps a granola bar like someone who has done this a hundred times.',
    urgent: 'Medic 1, stage right here. Nobody goes in until I call it secure. Understood?',
    after: 'Good work waiting. Jordan is getting help, and every one of us went home tonight.',
    monster: { cond: 'Behavioral Crisis (Unsecured Scene)', name: 'The Crisis Cyclone', draw: 'cyclone', hit: 'loses speed', win: 'settles into a light breeze' },
    patient: { look: 'jordan', pose: 'sit' },
    vitals: { Mental: 'Tearful, agitated, oriented', HR: '118/min', BP: '142/90', RR: '22/min', SpO2: '98%', Skin: 'Warm, flushed', BGL: 'Not checked' },
    steps: [
      { g: 0, label: 'Stage out of sight, a block away, with an exit route', hint: 'Where does an ambulance wait for a weapon call?',
        why: 'NH 2.4: request law enforcement and consider staging away until they clear the scene. Out of sight, clear way out, lights off near the scene.' },
      { g: 1, label: 'Wait for PD to radio "scene secure"', hint: 'The hardest skill in EMS is waiting.',
        why: 'Nobody is a hero on an unsecured weapon scene. Wait for the radio call. Staging is part of patient care, not a delay of it.',
        early: 'Waiting is right, but pick a safe staging spot first. Out of sight, with an exit.' },
      { g: 2, label: 'Approach with PD; keep the exit behind you', hint: 'Where is the door relative to you and to him?',
        why: 'NH says focus on crew safety. Go in with police, keep the door behind you, and never let the patient get between you and the exit.',
        early: 'Not yet. PD has not called the scene secure. The knife has not been accounted for.' },
      { g: 3, label: 'Verbal de-escalation: name, low voice, choices', hint: 'Talk first. What does respect sound like?',
        why: 'NH: attempt verbal de-escalation, and validate his feelings instead of minimizing them. Introduce yourself, use his name, speak low and slow, offer simple choices.',
        early: 'Talking is the right tool, but only once PD has secured the scene and you are inside with them.',
        vitals: { Mental: 'Calmer, answering questions', HR: '104/min' } },
      { g: 4, label: 'Screen for medical causes: glucose, SpO2, injuries, drugs', hint: 'Behavioral emergencies have medical mimics.',
        why: 'NH: consider causes such as hypoxia, hypoglycemia, and alcohol or drug intoxication. Check the sugar. Always. Result: 104 mg/dL.',
        early: 'You will screen for medical causes, but get the scene secure and the conversation going first.',
        vitals: { BGL: '104 mg/dL' } },
      { g: 4, label: 'Ask directly: "Are you thinking about killing yourself?"', hint: 'Does asking about suicide put the idea in their head?',
        why: 'NH: ask the patient directly if they have considered harming themselves or others. Asking does not plant the idea; it opens the door, and the ED needs the answer.',
        early: 'That question matters, but ask it once you are safely inside and he is talking with you.' },
      { g: 5, label: 'Transport for evaluation; he cannot refuse', hint: 'A person with a plan and a weapon. Can he refuse?',
        why: 'NH 2.4: a patient who is an active danger to self (for example, suicidal) may not refuse care. If he will not go, PD can help, including protective custody. Sit where you can reach the door.',
        early: 'Transport comes after he is safe, calm, and screened for medical causes.' },
    ],
    wrong: [
      { sev: 2, label: 'Go in now; PD is taking forever', why: 'Responders get hurt on scenes exactly like this. NH says stage until law enforcement clears the scene. Going in early can cost everything.' },
      { sev: 1, label: 'Park in front of the building, lights on', why: 'A lit-up ambulance in view can escalate a crisis and puts you in the line of danger. Stage out of sight.' },
      { sev: 2, label: 'Restrain him face-down for the ride', why: 'Face-down restraint can cause positional asphyxia and death. NH: restrain on the side, semi-sitting, or on the back. Prone only briefly to gain control. Never hog-tie. Watch his breathing the whole time.' },
      { sev: 1, label: 'Tell him to calm down', why: 'Nobody in history has calmed down after being told to calm down. Validate, then offer choices.' },
      { sev: 0, label: "Eat {partner}'s granola bar while you wait", why: '{partner} files this as a line-of-duty injury.' },
    ],
    numbers: ['Weapon or violence: stage until law enforcement clears the scene', 'Keep the exit behind you', 'Always check glucose in altered or agitated patients', 'Restraint: side, semi-sitting, or on the back; never hog-tie; watch breathing', 'Suicidal patients cannot refuse care in NH'],
    nh: ['Behavioral Emergencies (2.4)', 'Restraints (6.5)', 'Refusal of Care (8.14)', 'Police Custody (8.13)'],
    outro: 'Jordan got to the ED safely and agreed to talk to the crisis team. Nobody got hurt, which is the whole point.',
  },
  {
    id: 'arrest', tier: 0, boss: true, npc: 'doris', loc: 'The Hendersons\' house, east side', dir: 'east',
    title: 'Unresponsive in the Bathroom', domain: 'EMT boss: cardiac arrest, BLS',
    dispatch: 'Medic 1, Priority 1, the Henderson residence on the east side, for a 78-year-old male unresponsive in the bathroom. Caller states he has been in there since Jeopardy started. ALS is 15 minutes out.',
    scene: 'Harold, 78, is slumped on the toilet: gray, not responding, with an occasional gasp. The bathroom is 4 feet wide and very pink. A 1987 Reader\'s Digest is on the floor. Doris is on the phone with dispatch, doing her best.',
    urgent: 'He is in the bathroom and he will not answer me! Please hurry!',
    after: 'Harold is home and already arguing with the Jeopardy reruns. Thank you, sweetheart.',
    monster: { cond: 'Cardiac Arrest', name: 'The Porcelain Throne', draw: 'throne', hit: 'cracks', win: 'flushes itself away. For now.' },
    patient: { look: 'harold', pose: 'lie' },
    vitals: { Mental: 'Unresponsive', HR: 'No pulse', BP: 'None', RR: 'Agonal gasps', SpO2: 'No reading', Skin: 'Gray, cool' },
    steps: [
      { g: 0, label: 'Gloves on, scene safe; partner brings the AED and BVM', hint: 'Who goes in first, and with what?',
        why: 'NH Team Focused CPR: one crew member goes in fast with just gloves to start compressions while the other brings the AED and BVM. The AED never waits in the truck.' },
      { g: 1, label: 'Check breathing and carotid pulse together (10 sec max)', hint: 'Gasping. Is that breathing?',
        why: 'No pulse. Those gasps are agonal breathing, and agonal breathing is not breathing. This is cardiac arrest.',
        early: 'Confirm he is pulseless before you act on it.' },
      { g: 2, label: 'Drag him to the hallway floor', hint: 'Where can you do good CPR in a 4-foot bathroom?',
        why: 'NH 3.6: get the patient where a rescuer can kneel on both sides. A tiny bathroom is not a workspace. Move him fast.',
        early: 'Moving him is right, but confirm he is pulseless first. You do not drag a guy off the toilet because he is reading.' },
      { g: 3, label: 'Start compressions: 100-120/min, 2-2.4 in deep', hint: 'Hard, fast, center of the chest.',
        mini: { type: 'rhythm' },
        why: 'NH 3.6: at least 100 and under 120 compressions a minute, 2 to 2.4 inches deep, full recoil. Minimize every pause.',
        early: 'Compressions are right, but you cannot do quality CPR on a toilet. Get him on the floor first.' },
      { g: 4, label: 'AED pads on while your partner keeps compressing', hint: 'Every minute without a shock costs him.',
        why: 'NH: interrupt compressions only for the rhythm and pulse check and the shock. Pads go on while CPR continues.',
        early: 'The AED is key, but start compressions the moment he is on the floor. Pads go on while CPR runs.',
        vitals: { HR: 'AED: shock advised' } },
      { g: 5, label: '"Everybody clear!" Then shock', hint: 'The AED advised a shock. Who is touching him?',
        why: 'The AED advises a shock. Look, say it loud, make sure nobody is touching him. Then press. Keep the pause short.',
        early: 'Pads are not on yet. The AED cannot shock what it cannot see.' },
      { g: 6, label: 'Resume compressions immediately (no pulse check)', hint: 'Right after a shock, hands go where?',
        why: 'NH: resume compressions immediately after the shock. Two full minutes before the next rhythm and pulse check.',
        early: 'Resuming compressions after a shock is right. There has not been a shock yet.' },
      { g: 7, label: 'BVM: 1 breath every 10 compressions, no pause', hint: 'No advanced airway. How do breaths fit in?',
        why: 'NH runs compressions without stopping. Slip in 1 breath every 10 compressions, just enough for visible chest rise. Passive oxygen by non-rebreather is also allowed. More air is not better air.',
        early: 'Breaths matter, but compressions and the AED come first in adult arrest.',
        vitals: { HR: 'Pulse returns: 64/min', BP: '88/50', RR: 'Assisted', SpO2: '91%', Skin: 'Pinker' } },
      { g: 7, label: 'Swap compressors at least every 2 min; update incoming ALS', hint: 'Compression quality drops before you feel tired.',
        why: 'NH: switch compressors at least every two minutes to limit fatigue. Quality drops before the rescuer feels tired. Give ALS a quick update so they walk in ready.',
        early: 'Swapping comes at the 2-minute mark. Start the first cycle first.' },
    ],
    wrong: [
      { sev: 1, label: 'Start CPR right there on the toilet', why: 'A toilet is not a firm, flat surface. Neither is a bed. The floor, every time.' },
      { sev: 1, label: 'Check his pulse for a full 30 seconds to be sure', why: 'Pulse checks max out at 10 seconds. Longer means no blood to the brain while you count.' },
      { sev: 1, label: 'Check for a pulse right after the shock', why: 'NH: compressions resume immediately after the shock. Pulse checks happen with the rhythm check every 2 minutes.' },
      { sev: 1, label: 'Stop compressions every 30 for 2 breaths', why: 'NH does not pause for breaths in adult arrest. 1 breath every 10 compressions, compressions never stop.' },
      { sev: 2, label: 'Wait for ALS before starting CPR', why: 'NH: early high-quality CPR and early defibrillation are the most effective therapies. BLS keeps Harold alive. Start now.' },
      { sev: 0, label: 'Consult the 1987 Reader\'s Digest', why: '"Laughter Is the Best Medicine" is not in the resuscitation guidelines.' },
    ],
    numbers: ['Compressions: 100-120/min, 2-2.4 in, full recoil', 'Pulse check: 10 sec max, together with the rhythm check', 'No advanced airway: 1 breath every 10 compressions, no pause', 'Shock, then resume compressions immediately for 2 min', 'Swap compressors at least every 2 min'],
    nh: ['Cardiac Arrest - Adult (3.2A)', 'Team Focused CPR (3.6)', 'Airway Management Protocol - Adult (5.1A)'],
    outro: 'Harold got a pulse back before ALS arrived and should see Final Jeopardy again. In real life, about 1 in 10 people survive an out-of-hospital cardiac arrest. Fast, high-quality CPR and early defibrillation are what move that number.',
  },
  /* ---------------- AEMT level (boss: rollover) ---------------- */
  {
    id: 'hypo2', tier: 1, npc: 'june', loc: 'Pine Hollow Apartments, 1st floor', dir: 'far east',
    title: 'Double-Dosed Insulin', domain: 'AEMT: severe hypoglycemia, IV D10',
    dispatch: 'Medic 1, Priority 1, Pine Hollow Apartments, first floor, for a 67-year-old male, unresponsive. Wife states he is diabetic and took his insulin twice by mistake.',
    scene: 'Walt, 67, is slumped in his recliner, snoring, sweaty, and not responding to his name. A fishing show blares at full volume. June holds two insulin pens and a look of deep regret.',
    urgent: 'Walt took his insulin twice and now he will not wake up! Please!',
    after: 'Walt is back to yelling at the fishing show. I have labeled the pens. In big letters.',
    monster: { cond: 'Severe Hypoglycemia', name: 'The Goblin King', draw: 'goblinKing', hit: 'loses his crown for a second', win: 'abdicates the throne' },
    patient: { look: 'walt', pose: 'sit' },
    vitals: { Mental: 'Responds to pain only', HR: '104/min', BP: '146/88', RR: '14/min, snoring', SpO2: '94%', Skin: 'Pale, cool, drenched in sweat', BGL: 'Not checked' },
    steps: [
      { g: 0, label: 'PPE on; turn off the fishing show', hint: 'You need to hear his breathing.',
        why: 'Scene safe. Kill the TV so you can hear breath sounds and each other.' },
      { g: 1, label: 'Airway: reposition, NPA, suction ready', hint: 'Snoring plus a gag reflex. Which adjunct?',
        why: 'Snoring means a partly blocked airway. Reposition and place an NPA (he still has a gag reflex, so no OPA). Keep suction close.',
        early: 'Airway is right. Kill the noise first so you can actually hear it.',
        vitals: { RR: '14/min, quiet', SpO2: '97%' } },
      { g: 2, label: 'Check blood glucose', hint: 'Diabetic, double insulin, unresponsive.',
        why: 'Result: 24 mg/dL. That explains everything.',
        early: 'Sugar is the likely cause, but airway first. A snoring patient can obstruct while you poke his finger.',
        vitals: { BGL: '24 mg/dL' } },
      { g: 3, label: 'Establish an IV; confirm it flushes freely', hint: 'He cannot swallow. What route is left?',
        why: 'He cannot protect his airway, so nothing goes by mouth. Get a secure IV and flush it before you run anything through it.',
        early: 'IV access is coming. Confirm the sugar is low first.' },
      { g: 4, label: 'IV D10 (premixed bag preferred) until awake and BGL over 60', hint: 'IV in, sugar 24.',
        why: 'NH uses D10 only. Run it IV from a premixed bag or prefilled syringe until he is back to baseline and his sugar is over 60. No pump needed.',
        early: 'D10 is the fix, but you need a working IV first.',
        vitals: { Mental: 'Waking up, confused' } },
      { g: 5, label: 'Recheck glucose and mental status', hint: 'Did it work?',
        why: 'BGL 112 mg/dL. Walt asks why there are strangers in his living room and who changed the channel.',
        early: 'Recheck after you treat.',
        vitals: { Mental: 'Alert, grumpy', BGL: '112 mg/dL', HR: '88/min', Skin: 'Warm, drying' } },
      { g: 6, label: 'Transport: extra insulin can drop him again', hint: 'Which lasts longer, D10 or long-acting insulin?',
        why: 'Extra insulin, especially long-acting, can outlast the D10 by hours. Transport and keep rechecking his sugar. If he refuses, NH wants carbs and protein in him first.',
        early: 'Disposition comes after you confirm the treatment worked.' },
    ],
    wrong: [
      { sev: 2, label: 'Squeeze oral glucose into his mouth', why: 'He responds only to pain and cannot protect his airway. Oral glucose goes into the lungs. IV D10, or glucagon if no IV.' },
      { sev: 1, label: 'Push dextrose through an IV site that is swelling', why: 'A swelling site means infiltration. Stop, pull it, and start a new line. Dextrose in the tissue can cause serious injury.' },
      { sev: 1, label: 'Let him sleep it off; June will watch him', why: 'A sugar of 24 is a brain emergency, not a nap.' },
      { sev: 1, label: 'Insert an OPA', why: 'He has a gag reflex. An OPA can trigger vomiting. Use an NPA.' },
      { sev: 0, label: 'Change the channel to the Bruins', why: 'Morale improves. The patient does not.' },
    ],
    meh: [
      { label: 'Glucagon 1 mg IM', why: 'NH gives glucagon 1 mg IM when you cannot get an IV. With a working IV in, D10 is the NH first choice.' },
    ],
    numbers: ['Unresponsive + low sugar: IV D10, or glucagon 1 mg IM if no IV. Never oral.', 'D10 IV (premixed bag preferred) until back to baseline and BGL over 60', 'IO dextrose only for severe altered mental status or seizures with no IV', 'Gag reflex present: NPA, not OPA'],
    nh: ['Hypoglycemia - Adult (2.11A)', 'Routine Patient Care (1.0)', 'Airway Management Protocol - Adult (5.1A)'],
    outro: 'Walt ate a sandwich in the ambulance and critiqued your driving. June has color-coded the pens.',
  },
  {
    id: 'asthma', tier: 1, npc: 'lou', loc: 'Jaffrey Center craft fair, hay bale maze', dir: 'west',
    title: 'Lost in the Hay Maze', domain: 'AEMT: severe asthma, IM epinephrine',
    dispatch: 'Medic 1, Priority 1, the craft fair in Jaffrey Center, hay bale maze, for a 19-year-old female with asthma, trouble breathing. Her inhaler is empty.',
    scene: 'Maddie, 19, sits bolt upright on a hay bale, leaning forward on her hands. She can say two or three words at a time. Loud wheezes on every exhale. Her inhaler clicks uselessly.',
    urgent: 'Girl in the hay maze cannot breathe! Her puffer is empty! I got her out to the edge!',
    after: 'Maddie is fine. I am replacing the hay maze with a corn maze. Corn is cheaper anyway.',
    monster: { cond: 'Severe Asthma (Bronchospasm)', name: 'The Wheezing Wyrm', draw: 'wyrm', hit: 'loosens its coils', win: 'uncoils and slithers off' },
    patient: { look: 'maddie', pose: 'sit' },
    vitals: { Mental: 'Anxious, 2-3 word sentences', HR: '124/min', BP: '132/80', RR: '32/min, labored', SpO2: '90%', Skin: 'Pale, sweaty; neck muscles working' },
    steps: [
      { g: 0, label: 'Move her away from the hay dust; PPE', hint: 'What set this off?',
        why: 'Get her away from the trigger. Hay dust and mold are classic asthma triggers.' },
      { g: 1, label: 'Position of comfort: sitting up, leaning forward', hint: 'Should she lie down to rest?',
        why: 'NH: patients in respiratory distress should generally sit upright. Never lay her flat.',
        early: 'Positioning matters, but first get her out of the dust that caused this.' },
      { g: 2, label: 'Nebulized albuterol 2.5 mg, driven by oxygen', hint: 'Open the airways and add oxygen at the same time.',
        why: 'Albuterol relaxes the airway muscles. Drive the neb with oxygen so she gets both. In NH this is an EMT standing order, so it is already yours.',
        early: 'The neb is the treatment, but sit her up and get her out of the dust first.',
        vitals: { SpO2: '92%', RR: '28/min', Mental: '3-4 word sentences' } },
      { g: 3, label: 'Reassess: speech, work of breathing, SpO2, breath sounds', hint: 'How do you know it is working?',
        why: 'Only a little better. She is still using her neck muscles and cannot finish a sentence. A quieter chest can mean less air moving, not improvement.',
        early: 'Reassess after you treat something.' },
      { g: 4, label: 'Repeat albuterol (every 5 min for continued symptoms)', hint: 'Still wheezing after one neb.',
        why: 'NH: albuterol 2.5 mg by nebulizer, may repeat every 5 minutes for continued symptoms. DuoNeb is also an option, max 3 doses.',
        early: 'Reassess the first neb before you stack another.',
        vitals: { SpO2: '92%', RR: '28/min', Skin: 'Pale, tiring' } },
      { g: 5, label: 'Not responding: epinephrine 0.3 mg IM (1 mg/mL)', hint: 'Two nebs and she is tiring. What does the AEMT level add?',
        why: 'NH lets AEMTs give epinephrine 0.3 mg IM (auto-injector preferred, or 1 mg/mL drawn up) for severe asthma not responding to treatment. Call Medical Control for more doses.',
        early: 'Epinephrine is for severe asthma that is not responding. Give the nebs a fair shot first.',
        vitals: { SpO2: '96%', RR: '20/min', HR: '118/min', Mental: 'Full sentences', Skin: 'Pink, less sweaty' } },
      { g: 6, label: 'Transport; watch for tiring and a silent chest', hint: 'She improved. What could still go wrong?',
        why: 'Asthma can rebound. A tiring patient with a quiet chest is about to stop breathing. Be ready to assist with the BVM.',
        early: 'Transport after the treatment starts working.' },
    ],
    wrong: [
      { sev: 1, label: 'Lay her flat so she can rest', why: 'Lying flat makes breathing harder. Upright, leaning forward.' },
      { sev: 1, label: 'Have her breathe into a paper bag', why: 'Paper bags do not treat asthma, and rebreathing lowers oxygen. She needs oxygen and a bronchodilator.' },
      { sev: 1, label: 'Withhold oxygen; it makes asthmatics stop breathing', why: 'NH: keep SpO2 94-98% (90% in COPD). Hypoxic patients get oxygen.' },
      { sev: 2, label: 'Her chest went silent, so she is better; cancel transport', why: 'A silent chest means almost no air is moving. It is a pre-arrest sign. Assist ventilations and go.' },
      { sev: 0, label: 'Enter her in the hay bale toss to take her mind off it', why: 'She is not throwing anything. She can barely say "no."' },
    ],
    meh: [
      { label: 'CPAP right away', why: 'CPAP is an NH EMT order for respiratory distress, and it can help. But she needs a bronchodilator first, and she must be able to follow commands.' },
    ],
    numbers: ['Albuterol 2.5 mg neb, repeat every 5 min for continued symptoms (EMT order in NH)', 'Target SpO2 94-98% (90% in COPD)', 'AEMT adds: epinephrine 0.3 mg IM for severe asthma not responding', 'Danger signs: 1-2 word sentences, tiring, silent chest, falling SpO2'],
    nh: ['Asthma/COPD/RAD - Adult (2.3A)', 'Airway Management Procedure (5.0)', 'Continuous Positive Airway Pressure (CPAP) (5.4)'],
    outro: 'Maddie finished the ride speaking in full sentences, most of them about how much she hates hay.',
  },
  {
    id: 'rollover', tier: 1, boss: true, npc: 'trooper', loc: 'Route 124 (Turnpike Road)', dir: 'far northeast',
    title: 'Rollover: Fly Him to UMass', domain: 'AEMT boss: major trauma, air medical',
    dispatch: 'Medic 1, Priority 1, Route 124, Turnpike Road, east of downtown, for a single-vehicle rollover, one patient partially ejected. Fire and PD en route.',
    scene: 'An SUV lies on its side in the ditch. The driver, 22, is half out of the window, moaning. Deformed left thigh, bruised belly, pale and clammy. Drivers are slowing to film. The trauma center is UMass Memorial in Worcester, about an hour away by ground.',
    urgent: 'One patient, bad shape. Fire is stabilizing the vehicle. What do you need from us?',
    after: 'The helicopter was wheels-up 14 minutes after you called it. Textbook.',
    monster: { cond: 'Multi-System Trauma (Hemorrhagic Shock)', name: 'The Polytrauma Hydra', draw: 'hydra', hit: 'loses a head', win: 'runs out of heads' },
    patient: { look: 'driver', pose: 'lie' },
    vitals: { Mental: 'Confused, moaning', HR: '132/min', BP: '84/50', RR: '28/min', SpO2: '93%', Skin: 'Pale, cool, clammy' },
    steps: [
      { g: 0, label: 'Scene safety: traffic blocked, vehicle stabilized', hint: 'What kills responders at crash scenes?',
        why: 'Traffic kills responders. Park to block, set cones, and let fire stabilize the vehicle before anyone climbs on it.' },
      { g: 1, label: 'Primary: bleeding, airway, breathing, circulation; recognize shock', hint: 'Fast primary. What do BP 84 and pale, clammy skin tell you?',
        why: 'No spurting bleed. Airway open, breathing fast, pulse weak and fast, skin pale and cool, confused. NH 4.6: pale, cool, clammy skin with tachycardia and hypotension is shock. He meets high-risk trauma criteria.',
        early: 'Get the scene safe first. Traffic and an unstable vehicle can turn one patient into four.' },
      { g: 2, label: 'Request air medical NOW, before packaging', hint: 'An hour by ground to the trauma center. When do you ask for the helicopter?',
        why: 'NH 8.0 criteria fit: sustained SBP under 90, and ground time to definitive care longer than the helicopter ETA. Request early. The aircraft flies while you package, and you can always cancel.',
        early: 'Air medical is the right call, but do a fast primary first so you know what you are asking for.' },
      { g: 3, label: 'Package: spinal motion restriction per protocol, splint, keep warm', hint: 'Minutes, not tens of minutes. And cold trauma patients bleed more.',
        why: 'Rollover with ejection and an altered patient means spinal motion restriction per NH 4.7. Splint the leg. NH 4.6: keep him warm and prevent heat loss.',
        early: 'Packaging is coming. Get the helicopter moving first so it flies while you work.',
        vitals: { Skin: 'Pale, warming', BP: '88/54' } },
      { g: 3, label: 'Set up the LZ: flat, clear, at least 100 x 100 ft, wires reported', hint: 'The field next to the road. What does the pilot need?',
        why: 'Pick a flat, open area (100 x 100 feet is a common minimum; check your air service), clear of wires, poles, and loose debris. Mark it and radio every hazard. NH 8.0 also allows an airport, and Jaffrey\'s airport is right up Route 124. The pilot has the final say on the site.',
        early: 'You will need an LZ, but request the aircraft first. No request, no helicopter.' },
      { g: 3, label: 'IV access; 250 mL boluses to a radial pulse and clear mentation', hint: 'He is in shock with no head injury. How much fluid?',
        why: 'NH 4.6: small boluses (about 250 mL) until he has a palpable radial pulse or a clearer head, not a normal BP. Max 2 L without Medical Control. Never delay transport for an IV.',
        early: 'Fluids help, but the helicopter request comes first. The aircraft flies while you start the line.',
        vitals: { HR: '124/min', BP: '92/58', Mental: 'Confused, answering' } },
      { g: 4, label: 'Approach the aircraft only when the crew signals, from the front', hint: 'Which part of a helicopter is nearly invisible?',
        why: 'Wait for the crew to wave you in, and approach from the front, in the pilot\'s view. The tail rotor is nearly invisible and it does not forgive.',
        early: 'The helicopter is not on the ground yet. Finish packaging and the LZ.' },
      { g: 5, label: 'Hand off with a MIST report', hint: 'Mechanism, Injuries, Signs, ...?',
        why: 'MIST: Mechanism, Injuries, Signs, Treatment. Thirty seconds, clear and in order. Then let them fly.',
        early: 'Handoff happens at the aircraft, once the crew is ready for you.' },
    ],
    wrong: [
      { sev: 1, label: 'Wait until he is packaged to call the helicopter', why: 'Minutes matter in hemorrhagic shock. Request early; the aircraft flies while you package.' },
      { sev: 2, label: 'Walk up to the aircraft from the back to save time', why: 'The tail rotor. Never. Approach from the front, only when the crew signals.' },
      { sev: 1, label: 'Put the LZ by the power lines; it is the flattest spot', why: 'Wires are nearly invisible from the air and a known killer of helicopter crews. Pick a clear field and report every wire.' },
      { sev: 1, label: 'Give him water; he says he is thirsty', why: 'Nothing by mouth. He may need surgery and he may vomit. Thirst is a sign of shock.' },
      { sev: 1, label: 'Run IV fluids wide open until his BP is normal', why: 'Big volumes dilute clotting factors and blow off clots. NH: 250 mL boluses to a radial pulse or clear mentation, max 2 L.' },
      { sev: 0, label: 'Take a selfie with the helicopter', why: 'The flight crew has seen this before. The flight crew is not impressed.' },
    ],
    numbers: ['High-risk trauma: closest Level 1 or 2 trauma center; request air early, cancel if not needed', 'Hemorrhagic shock: 250 mL boluses to a radial pulse or clear mentation, max 2 L. Head injury: SBP over 110.', 'LZ: flat, clear, 100 x 100 ft is a common minimum (check your air service)', 'Approach only when signaled, from the front, never the tail', 'Handoff: MIST (Mechanism, Injuries, Signs, Treatment)'],
    nh: ['Trauma Triage and Transport Decision (8.17)', 'Air Medical Transport (8.0)', 'Shock - Traumatic (4.6)', 'Spinal Injury (4.7)', 'Musculoskeletal Injuries (4.5)', 'LZ setup and aircraft approach: air service standards, not in NH PCP'],
    outro: 'The helicopter lifted off for UMass Memorial 14 minutes after you called it. He went straight to the OR and is expected to walk again. The drivers who stopped to film are still stuck in traffic.',
  },
  /* ---------------- Paramedic level (boss: arrest2) ---------------- */
  {
    id: 'stemi', tier: 2, npc: 'kevin', loc: 'Cubicle Keep, downtown Jaffrey, corner office', dir: 'northeast',
    title: 'Chest Pain in the Corner Office', domain: 'Paramedic: STEMI, 12-lead',
    dispatch: 'Medic 1, Priority 1, Cubicle Keep, corner office, 58-year-old male with chest pain and sweating. Caller states he "thought it was the tacos."',
    scene: 'Mr. Pemberton, the CEO, is pale and sweaty, pressing a fist into the center of his chest. The pain started 40 minutes ago during a budget meeting. He admits he took "one of those little blue pills" last night. Kevin from IT is hovering.',
    urgent: 'It is the CEO this time! Chest pain! He says it is the tacos but he looks really gray!',
    after: 'Mr. Pemberton is back. He approved a raise for the whole IT department. Coincidence? Absolutely not.',
    monster: { cond: 'Inferior STEMI (RV Involvement)', name: 'The Occlusion Ogre', draw: 'ogre', hit: 'drops its cheeseburger club', win: 'gets ballooned into oblivion' },
    patient: { look: 'pemberton', pose: 'sit' },
    vitals: { Mental: 'Alert, anxious', HR: '58/min', BP: '96/62', RR: '20/min', SpO2: '95%', Skin: 'Pale, cool, sweaty' },
    steps: [
      { g: 0, label: 'PPE, scene safe, sit him down', hint: 'Start simple.',
        why: 'Scene safe. Sit him down and stop him from walking. Exertion raises the heart\'s oxygen demand.' },
      { g: 1, label: '12-lead ECG within 10 minutes; transmit it', hint: 'Chest pain plus sweating. What test comes first?',
        why: 'NH: 12-lead within 10 minutes, transmitted per local guidelines. ST elevation in II, III, and aVF with reciprocal changes: inferior STEMI.',
        early: 'Scene first, then the 12-lead immediately.' },
      { g: 1, label: 'Aspirin 324 mg, chewed, unless allergy or GI bleeding', hint: 'A cheap drug that saves heart muscle.',
        why: 'Chewed aspirin slows clot growth. NH dose is 324 mg. Skip it for aspirin or NSAID anaphylaxis, active GI bleeding, or if he already took 324 mg in the last 30 minutes.',
        early: 'Aspirin is right, but get the scene settled first.' },
      { g: 2, label: 'Right-sided ECG: check V4R', hint: 'Inferior STEMI. Which ventricle might also be involved?',
        why: 'NH 6.0: for a suspected inferior MI, consider a right-sided ECG. ST elevation in V4R means the right ventricle is involved, and a right-sided MI depends on preload.',
        early: 'Get the standard 12-lead first. V4R is the follow-up question.' },
      { g: 3, label: 'STEMI Alert: notify the receiving facility early', hint: 'Who needs to know before you arrive?',
        why: 'NH: notify the receiving facility of a "STEMI Alert" and transmit the 12-lead. Early activation shortens the time to open the artery.',
        early: 'Finish the ECG workup first so the alert is complete.' },
      { g: 3, label: 'IV (avoid the right wrist); 250 mL bolus for low BP', hint: 'Right-sided MI plus a soft pressure. What does the RV need?',
        why: 'NH asks you to avoid the right wrist for IVs in ACS; the cath lab often goes in there. A right-sided MI with a soft BP needs volume: 250 mL at a time, recheck lungs and BP after each.',
        early: 'You will need access, but confirm what kind of MI this is first.',
        vitals: { BP: '108/68' } },
      { g: 4, label: 'Transport per your local STEMI plan (PCI center)', hint: 'Where does a STEMI go?',
        why: 'NH: transport to the most appropriate facility under local STEMI guidelines, usually a hospital with a cath lab. Time is muscle.',
        early: 'Transport is the last step here. Make the alert and fix the pressure first.' },
    ],
    wrong: [
      { sev: 2, label: 'Nitroglycerin 0.4 mg SL now', why: 'Three strikes. NH gives nitro only while SBP stays over 100 (his is 96) and never after a PDE-5 inhibitor (the "blue pill" last night). A right-sided MI makes it worse. Hold it.' },
      { sev: 1, label: 'Skip the 12-lead; the hospital will do one', why: 'NH calls the transmitted 12-lead critical to activating the STEMI system. The cath lab team gets moving before he arrives.' },
      { sev: 1, label: 'High-flow oxygen by non-rebreather', why: 'SpO2 is 95% and he is not short of breath. NH gives oxygen in ACS only for SpO2 under 94%, dyspnea, or heart failure, titrated to 94-98%.' },
      { sev: 1, label: 'Agree it was probably the tacos', why: 'Chest pain with sweating in a 58-year-old is a heart attack until proven otherwise.' },
      { sev: 0, label: 'Ask for a raise while he is vulnerable', why: 'Ethically questionable. Tactically brilliant. Clinically useless.' },
    ],
    numbers: ['12-lead within 10 min; transmit it', 'Inferior STEMI: II, III, aVF; consider a right-sided ECG (V4R)', 'Nitro: only if SBP > 100; never after a PDE-5 inhibitor; caution in RV infarct', 'ACS oxygen: only if SpO2 < 94%, dyspnea, or heart failure; target 94-98%', 'Aspirin 324 mg chewed (skip if 324 mg taken in the last 30 min)'],
    nh: ['Acute Coronary Syndrome - Adult (3.0)', '12 Lead Acquisition (6.0)', 'Shock - Non-traumatic (2.22)'],
    outro: 'The cath lab opened his right coronary artery 62 minutes after you walked in. He is already emailing from his hospital bed.',
  },
  {
    id: 'brady', tier: 2, npc: 'clerk', loc: 'Gas-n-Go, Route 202 north', dir: 'north',
    title: 'Fainted at the Scratch Tickets', domain: 'Paramedic: symptomatic bradycardia',
    dispatch: 'Medic 1, Priority 1, Gas-n-Go on Route 202, for an 81-year-old male who fainted at the scratch-ticket counter.',
    scene: 'Mr. Fitch, 81, is on the floor, awake but gray and confused, still holding a losing ticket. He says he feels woozy. His med list includes metoprolol.',
    urgent: 'Mr. Fitch fainted by the scratch tickets! He is awake but he looks gray!',
    after: 'Mr. Fitch came back with a pacemaker and bought one ticket. Won two dollars. He called it his lucky day.',
    monster: { cond: 'Symptomatic Bradycardia (3rd-Degree Block)', name: 'The Slowpoke Sovereign', draw: 'snail', hit: 'speeds up slightly', win: 'is lapped by a paced rhythm' },
    patient: { look: 'fitch', pose: 'lie' },
    vitals: { Mental: 'Confused, slow to answer', HR: '34/min', BP: '72/40', RR: '18/min', SpO2: '93%', Skin: 'Gray, cool, sweaty' },
    steps: [
      { g: 0, label: 'PPE, scene safe, lay him flat', hint: 'Low BP. Position?',
        why: 'He already fainted once. Keep him flat and stop him from getting up.' },
      { g: 1, label: 'Monitor, 12-lead, oxygen to 94-98%', hint: 'HR 34. What is the rhythm?',
        why: 'HR 34 with low BP and confusion: symptomatic, unstable bradycardia. The 12-lead shows third-degree (complete) heart block. NH also asks you to think about causes: ACS, hyperkalemia, hypoxia, hypothermia.',
        early: 'Scene and position first.',
        vitals: { SpO2: '95%' } },
      { g: 2, label: 'IV access', hint: 'Meds need a route.',
        why: 'Get IV access quickly, but do not let it delay pacing if he gets worse.',
        early: 'Identify the rhythm first.' },
      { g: 3, label: 'Atropine 1 mg IV (every 3-5 min, max 3 mg)', hint: 'First drug NH lists for unstable bradycardia.',
        why: 'NH 3.1A: consider atropine 1 mg IV every 3-5 minutes, max 3 mg. It often fails in third-degree block below the AV node, so do not let it delay pacing.',
        early: 'Atropine needs an IV.',
        vitals: { HR: '36/min' } },
      { g: 4, label: 'Transcutaneous pacing: raise mA to capture, confirm femoral pulse', hint: 'Atropine barely moved the rate. Next?',
        why: 'Pads on, set a rate (60-80 is common), raise the milliamps until every spike has a wide QRS after it, then confirm a pulse at the femoral artery (ACLS practice).',
        early: 'Pacing is the likely next step, but atropine is quick. Try it first unless he is crashing.',
        vitals: { HR: '70/min, paced', BP: '104/62', Mental: 'Clearer', Skin: 'Pinker' } },
      { g: 5, label: 'Procedural sedation during pacing, per protocol', hint: 'Pacing feels like being punched every second.',
        why: 'Pacing hurts. NH says sedate before or during pacing when feasible, for example midazolam 2.5 mg IV (may repeat once in 5 minutes) or ketamine 10-20 mg IV over 10 minutes. Go easy with a soft BP.',
        early: 'Get pacing started first. Sedate during pacing if you can.' },
      { g: 6, label: 'Transport; vasopressor is the backup if pacing fails', hint: 'If pacing fails, what does NH list next?',
        why: 'NH backups: epinephrine infusion 2-10 mcg/min, norepinephrine 1-80 mcg/min, or push-dose epinephrine 10-20 mcg every 2 minutes. Contact Medical Control and transport to a center that can place a pacemaker.',
        early: 'Stabilize first.' },
    ],
    wrong: [
      { sev: 2, label: 'Adenosine 6 mg rapid IV push', why: 'Adenosine slows the heart further. It is for SVT, never for bradycardia.' },
      { sev: 1, label: 'Keep repeating atropine past 3 mg', why: 'NH max is 3 mg. More atropine will not fix a block below the AV node. Pace.' },
      { sev: 1, label: 'Check a carotid pulse to confirm pacing capture', why: 'Pacing makes muscles jump, which can feel like a pulse at the neck. Use the femoral pulse.' },
      { sev: 1, label: 'Stand him up to see if he can sign a refusal', why: 'He will faint again, maybe onto the lottery machine. NH: patients who lack capacity cannot refuse care.' },
      { sev: 0, label: 'Buy him another scratch ticket for luck', why: 'He appreciates it. His heart rate does not.' },
    ],
    numbers: ['Atropine 1 mg IV every 3-5 min, max 3 mg', 'Pacing: rate commonly 60-80, raise mA to capture, check femoral pulse', 'Sedate before or during pacing if feasible (midazolam 2.5 mg IV, or ketamine 10-20 mg IV over 10 min)', 'Backups: epinephrine 2-10 mcg/min, norepinephrine 1-80 mcg/min, push-dose epi 10-20 mcg', 'Beta blocker overdose: NH lists glucagon up to 5 mg IV'],
    nh: ['Bradycardia - Adult (3.1A)', '12 Lead Acquisition (6.0)', 'Refusal of Care (8.14)', 'Pacing rate and capture check: ACLS, not in NH PCP'],
    outro: 'Mr. Fitch got a permanent pacemaker the next morning. He says the ride was the most exciting thing to happen at the Gas-n-Go since the slushie machine fire.',
  },
  {
    id: 'arrest2', tier: 2, boss: true, npc: 'doris', loc: 'The Hendersons\' house. Again.', dir: 'east',
    title: 'The Throne Returns', domain: 'Paramedic boss: VF arrest, ACLS',
    dispatch: 'Medic 1, Priority 1, the Henderson residence. Again. 80-year-old male unresponsive in the bathroom. Caller states it is Harold\'s twin brother Gerald, visiting for the week.',
    scene: 'Same bathroom. Same pink tile. Same Reader\'s Digest. Gerald is gray and gasping, and Doris has already dragged him into the hallway and started compressions. She took a CPR class after last time.',
    urgent: 'It is Gerald this time! Harold\'s twin! I already started CPR like they taught me! Hurry!',
    after: 'Harold and Gerald now take turns in that bathroom. With the door unlocked. My rule.',
    monster: { cond: 'VF Cardiac Arrest', name: 'The Porcelain Throne, Ascended', draw: 'throneAsc', hit: 'cracks down the middle', win: 'is flushed from this world for good' },
    patient: { look: 'gerald', pose: 'lie' },
    vitals: { Mental: 'Unresponsive', HR: 'No pulse', BP: 'None', RR: 'Agonal gasps', SpO2: 'No reading', Skin: 'Gray, cool', Rhythm: 'Unknown' },
    steps: [
      { g: 0, label: 'Take over CPR from Doris without a pause; pads on', hint: 'Doris is doing CPR. What do you do first?',
        mini: { type: 'rhythm' },
        why: 'NH Team Focused CPR: one crew member goes straight to the chest. Swap in for Doris without a gap and get pads on while compressions continue.' },
      { g: 1, label: 'Rhythm check: VF. Charge, clear, shock at max energy', hint: 'Pads are on. What does the monitor show?',
        why: 'VF is shockable. NH: defibrillate at the device\'s maximum energy. Check the pulse at the same time as the rhythm, and keep the pause short.',
        early: 'Pads first, then rhythm.',
        vitals: { Rhythm: 'Ventricular fibrillation' } },
      { g: 2, label: 'Resume CPR immediately for 2 minutes', hint: 'Right after the shock.',
        why: 'NH: resume compressions immediately after the shock. Two full minutes. No pulse check.',
        early: 'Not yet. Check the rhythm and shock first.' },
      { g: 3, label: 'IV or IO access without stopping compressions', hint: 'You will need a route for drugs.',
        why: 'NH: place the IV or IO without interrupting chest compressions.',
        early: 'Access matters, but shock first and get compressions going.' },
      { g: 4, label: 'Still VF: shock, then epinephrine 1 mg IV/IO', hint: 'Second rhythm check, still VF.',
        why: 'NH: after the first 2-minute cycle, epinephrine 1 mg IV/IO (0.1 mg/mL), then repeat every other cycle.',
        early: 'Epinephrine needs IV or IO access first.' },
      { g: 5, label: 'Still VF: shock, then amiodarone 300 mg IV/IO', hint: 'Third check. Refractory VF.',
        why: 'NH: anti-dysrhythmic per ACLS, which means amiodarone 300 mg first and 150 mg second, or lidocaine. Still VF after 3 shocks? NH also allows double sequential defibrillation, or moving the pads to anterior-posterior.',
        early: 'Anti-dysrhythmics come after the shocks and epinephrine.' },
      { g: 6, label: 'After 8 minutes: advanced airway with waveform capnography', hint: 'NH timing for the advanced airway? And how do you confirm it?',
        why: 'NH: BVM for the first 4 cycles (8 minutes), then place an ETT or supraglottic airway without stopping compressions. Waveform ETCO2 confirms the tube and tracks CPR: NH wants at least 20 mmHg. Ventilate 1 breath every 10 compressions.',
        early: 'BVM for the first 4 cycles (8 minutes). Shocks and drugs come first.' },
      { g: 7, label: 'ETCO2 jumps from 22 to 45: pulse check', hint: 'A sudden rise in ETCO2 means?',
        why: 'NH 6.1: an abrupt ETCO2 rise is a reasonable sign of return of spontaneous circulation. Pulse present!',
        early: 'Watch the capnography. You need an airway and ETCO2 first.',
        vitals: { HR: 'Pulse: 98/min', BP: '86/50', RR: 'Assisted, 10/min', SpO2: '90%', Rhythm: 'Sinus rhythm', Skin: 'Pinker' } },
      { g: 8, label: 'Post-ROSC care: SpO2 94-98%, treat low BP, 12-lead', hint: 'You got him back. Now keep him.',
        why: 'NH 3.4: ventilate 10-12 a minute to ETCO2 35-40, keep SpO2 94-98%, keep SBP over 90 or MAP at least 65 (250 mL boluses, then pressors), and get a 12-lead at least 8 minutes after ROSC. STEMI on it? Call a STEMI Alert.',
        early: 'You do not have a pulse yet.',
        vitals: { BP: '104/66', SpO2: '96%' } },
    ],
    wrong: [
      { sev: 1, label: 'Stop compressions to intubate', why: 'NH: intubate without interrupting compressions, and not until after 4 cycles. BVM is fine early.' },
      { sev: 1, label: 'Epinephrine before the first shock', why: 'In VF the shock comes first. NH gives epinephrine after the first 2-minute cycle.' },
      { sev: 1, label: 'Amiodarone 150 mg as the first dose', why: 'ACLS first dose in arrest is 300 mg. 150 mg is the second dose.' },
      { sev: 1, label: 'Bag at 30 breaths a minute to "get oxygen in"', why: 'Hyperventilation raises chest pressure and cuts blood return to the heart. NH: 1 breath every 10 compressions, without pausing.' },
      { sev: 1, label: 'Pulse check after every shock', why: 'Resume CPR right after the shock. NH checks the pulse with the rhythm, every 2 minutes.' },
      { sev: 0, label: 'Ask Gerald if he is related to Harold', why: 'He is. It explains a lot.' },
    ],
    numbers: ['VF: shock at max energy, CPR 2 min, then epinephrine 1 mg every other cycle', 'Anti-dysrhythmic per ACLS: amiodarone 300 mg, then 150 mg', 'Refractory VF after 3 shocks: double sequential defib or anterior-posterior pads', 'Advanced airway after 4 cycles (8 min); 1 breath every 10 compressions; ETCO2 at least 20', 'Post-ROSC: SpO2 94-98%, SBP > 90 or MAP >= 65, 12-lead at 8+ min'],
    nh: ['Cardiac Arrest - Adult (3.2A)', 'Team Focused CPR (3.6)', 'Capnography (6.1)', 'Double Sequential Defibrillation (6.2)', 'Supraglottic Airways (5.12)', 'Post Resuscitative Care (3.4)'],
    outro: 'Gerald is awake in the ICU, complaining about the hospital pudding. Doris has been nominated for a community lifesaver award. The Porcelain Throne has been replaced with a low-flow model.',
  },
];

window.JRMA.PEARLS = {
  '1,1': { title: 'Peer support is a skill', text: 'About 1 in 10 ambulance workers screens positive for PTSD, and depression and anxiety run higher than in the general public. Talking early, to peers, a CISM team, or a counselor, is standard practice. It is not weakness.' },
  '0,0': { title: 'Junctional bleeding', text: 'Groin, armpit, and neck wounds cannot take a limb tourniquet. NH: pack the wound with hemostatic dressing (or plain gauze if that is all you have) and hold hard, direct pressure. Carry a junctional tourniquet? This is its moment.' },
  '1,0': { title: 'Carbon monoxide lies', text: 'NH: oxygen saturation may be inaccurate after carbon monoxide or cyanide exposure. A normal SpO2 does not rule out CO. A whole household with headaches and nausea? Think CO. Get everyone out.' },
  '2,0': { title: 'Stroke screen', text: 'NH stroke screen: facial droop, arm drift, speech. Any abnormal finding is positive; then score severity (for example, FAST-ED). Record the last known well: the last time the patient was at their baseline, not when they were found. Check glucose; low sugar mimics stroke.' },
  '0,1': { title: 'Babies are not small adults', text: 'NH: in infants and neonates, a heart rate under 60/min with poor perfusion, despite good oxygenation and ventilation, means start CPR.' },
  '2,1': { title: 'The Golden Hour, fact-checked', text: 'The "golden hour" is more slogan than science. A 2001 review found little evidence for a hard 60-minute cutoff. The lesson still holds: time matters for bleeding, strokes, and heart attacks, so do not waste it.' },
  '3,0': { title: 'Trauma triage red flags', text: 'NH high-risk (RED) trauma includes: penetrating injury to the head, neck, torso, or upper arms and thighs; suspected pelvic fracture; flail chest; amputation above the wrist or ankle; bleeding that needs a tourniquet or packing; room-air SpO2 under 90%. They go to the closest Level 1 or 2 trauma center.' },
  '3,1': { title: 'Ask the question', text: 'Asking someone directly whether they are thinking about suicide does not increase their risk. It opens the conversation. The 988 Suicide & Crisis Lifeline takes calls and texts 24/7.' },
};
