/* Legend of JRMA: license trials (phase 2 of each level's boss).
 *
 * Beat a level's boss call, then pass its trial to advance:
 *   trial-emt   -> AEMT license
 *   trial-aemt  -> Paramedic license
 *   trial-medic -> "Legend of JRMA" title (Paramedic is NH's top license)
 * Each trial tests the scope of the level you just finished.
 *
 * STATUS: checked line by line against the State of New Hampshire Patient
 * Care Protocols v9.3 (effective 2025-11-07). `nh` names the section. Where
 * NH is silent, `nh` says so and names the national source instead.
 * `verified: true` means the question was checked against v9.3.
 *
 * Question fields: q (question), c (choices), a (index of the correct
 * choice), why (explanation), nh (NH protocol section), verified (boolean).
 */
window.JRMA = window.JRMA || {};

window.JRMA.EXAMS = {
  'trial-emt': {
    id: 'trial-emt', type: 'exam', level: 1, grants: 'AEMT', npc: 'drhale', count: 8, misses: 2,
    title: 'EMT Trial: Earn Your AEMT', loc: 'JRMA Station', dir: 'home',
    domain: 'Phase 2 boss: EMT-level protocols',
    urgent: 'Phase two. Prove you know your EMT protocols and the AEMT license is yours. Eight questions. Miss three and the Binder wins.',
    after: 'AEMT now. IVs, D10, nitro, and more meds. Keep reading: protocols change more often than the coffee filter.',
    monster: { cond: 'The Protocol Binder', name: 'Binder of Infinite Pages', draw: 'binder', hit: 'loses a page', win: 'snaps its rings shut in defeat' },
    bank: [
      { q: 'Adult CPR compression rate?',
        c: ['60-80 per minute', '100-120 per minute', '130-150 per minute', 'As fast as possible'], a: 1,
        why: 'NH 3.6: at least 100 and under 120 a minute. Faster than 120 cuts refill time and depth.',
        nh: 'Team Focused CPR (3.6)', verified: true },
      { q: 'Adult compression depth?',
        c: ['About 1 inch', '1.5 inches', '2 to 2.4 inches', 'At least 3 inches'], a: 2,
        why: 'NH 3.6: 2 to 2.4 inches, with full recoil between compressions.',
        nh: 'Team Focused CPR (3.6)', verified: true },
      { q: 'Adult cardiac arrest, no advanced airway. How does NH want you to ventilate?',
        c: ['30 compressions, pause, 2 breaths', '1 breath every 10 compressions, no pause', '15 compressions to 2 breaths', 'No breaths for the first 10 minutes'], a: 1,
        why: 'NH 3.2A: BVM 1 breath every 10 compressions without interrupting compressions. Passive oxygen by non-rebreather is also allowed.',
        nh: 'Cardiac Arrest - Adult (3.2A)', verified: true },
      { q: 'Unresponsive adult, no normal breathing, occasional gasps. Pulse unclear after 10 seconds. Next?',
        c: ['Recheck the pulse for 30 more seconds', 'Start compressions', 'Give oxygen by non-rebreather', 'Place in recovery position'], a: 1,
        why: 'Gasping (agonal breathing) is not breathing. If you are not sure about a pulse within 10 seconds, start compressions.',
        nh: 'Not detailed in NH PCP; 3.2A defers to AHA BLS', verified: true },
      { q: 'Adult with a pulse but ineffective breathing. BVM rate?',
        c: ['1 breath every 2-3 seconds', '10-12 breaths a minute', '1 breath every 15 seconds', '2 breaths every 30 seconds'], a: 1,
        why: 'NH 1.0: adults 10-12 breaths a minute with 100% oxygen, each just enough for visible chest rise.',
        nh: 'Routine Patient Care (1.0)', verified: true },
      { q: 'Where does a limb tourniquet go on a safe scene?',
        c: ['Directly over the wound', 'On bare skin, 2-3 inches above the wound, not over a joint', 'On the joint above the wound', 'Below the wound'], a: 1,
        why: 'NH 4.4: on the skin, 2-3 inches above the bleeding site, never over a joint. Only on an unsafe scene do you go high on the limb over clothing.',
        nh: 'Hemorrhage Control (4.4)', verified: true },
      { q: 'NH defines a hypoglycemic emergency as:',
        c: ['Glucose under 80 with no symptoms', 'Glucose under 60 with altered mental status', 'Glucose under 40 only', 'Any diabetic who feels shaky'], a: 1,
        why: 'NH 2.11A: glucose under 60 mg/dL with altered mental status.',
        nh: 'Hypoglycemia - Adult (2.11A)', verified: true },
      { q: 'Which patient can receive oral glucose?',
        c: ['Unresponsive with a glucose of 40', 'Confused but able to swallow and protect the airway, glucose of 48', 'Seizing, glucose unknown', 'Anyone diabetic, just in case'], a: 1,
        why: 'NH 2.11A: glucose gel 15-30 g, only if the patient is alert enough to swallow and protect the airway. Otherwise EMTs give IN glucagon or a glucagon auto-injector.',
        nh: 'Hypoglycemia - Adult (2.11A)', verified: true },
      { q: 'Epinephrine auto-injector dose for a 20 kg child in anaphylaxis?',
        c: ['0.15 mg (EpiPen Jr)', '0.3 mg (adult EpiPen)', '0.5 mg', '1 mg'], a: 0,
        why: 'NH: 0.15 mg under 25 kg, 0.3 mg at 25 kg and up. Outer thigh. May repeat in 5 minutes if symptoms do not resolve.',
        nh: 'Allergic Reaction/Anaphylaxis - Pediatric (2.2P)', verified: true },
      { q: 'Suspected cardiac chest pain, no aspirin allergy, no GI bleeding, no aspirin today. NH dose?',
        c: ['81 mg swallowed whole', '324 mg chewed', '1,000 mg', 'Only if BP is over 160'], a: 1,
        why: 'NH 3.0: aspirin 324 mg chewable, unless the patient already took 324 mg in the last 30 minutes.',
        nh: 'Acute Coronary Syndrome - Adult (3.0)', verified: true },
      { q: 'Opioid overdose with slow breathing. NH intranasal naloxone dose?',
        c: ['0.04 mg in one nostril', '1 mg per nostril (2 mg total) or a 4 mg nasal spray', '10 mg in one nostril', 'Only IV naloxone is allowed'], a: 1,
        why: 'NH 2.17A: 1 mg per nostril by atomizer (2 mg total) or a 4 mg nasal spray. Titrate to breathing, not wakefulness.',
        nh: 'Opioid Overdose - Adult (2.17A)', verified: true },
      { q: 'How do you size an oropharyngeal airway (OPA)?',
        c: ['Nose to chin', 'Corner of the mouth to the earlobe or angle of the jaw', 'Front teeth to the Adam\'s apple', 'Width of the patient\'s pinky'], a: 1,
        why: 'Corner of the mouth to the earlobe (or angle of the jaw). Use an OPA only if there is no gag reflex.',
        nh: 'Not in NH PCP; national EMT curriculum', verified: true },
      { q: 'Dispatch reports a person with a knife threatening self-harm. PD is en route. What do you do?',
        c: ['Go in quickly before it escalates', 'Stage away until law enforcement clears the scene', 'Park in front with lights on so they know help is here', 'Refuse the call'], a: 1,
        why: 'NH 2.4: request law enforcement support and consider staging away until law enforcement has cleared the scene.',
        nh: 'Behavioral Emergencies (2.4)', verified: true },
      { q: 'A suicidal patient with capacity says no to transport. Under NH protocol?',
        c: ['They may refuse; get a signature', 'They may not refuse care', 'Leave them with family', 'Call back in an hour'], a: 1,
        why: 'NH 2.4: a patient who lacks capacity or is an active danger to self or others (for example, suicidal) may not refuse care.',
        nh: 'Behavioral Emergencies (2.4); Refusal of Care (8.14)', verified: true },
      { q: 'A combative patient needs restraint. Which is never acceptable?',
        c: ['Supine (on the back)', 'Lateral (on the side)', 'Hog-tied, or left face down for transport', 'Semi-recumbent (semi-sitting)'], a: 2,
        why: 'NH 6.5: restrain lateral, semi-recumbent, or supine. Prone only briefly to gain control, since it can kill. Never hog-tie. Watch breathing the whole time.',
        nh: 'Restraints (6.5)', verified: true },
      { q: 'Which is an EARLY sign of shock?',
        c: ['Low blood pressure', 'Fast heart rate and anxiety', 'Fixed, dilated pupils', 'Slow breathing'], a: 1,
        why: 'NH 2.22 lists anxiety, tachycardia, tachypnea, and sweating as compensated shock. Low blood pressure comes late.',
        nh: 'Shock - Non-traumatic (2.22)', verified: true },
      { q: 'Non-rebreather mask flow rate per NH?',
        c: ['2 L/min', '4-6 L/min', 'At least 8 L/min, up to flush', 'No flow; the bag does it'], a: 2,
        why: 'NH 5.0: at least 8 L/min, up to flush rate. Enough to keep the reservoir bag full.',
        nh: 'Airway Management Procedure (5.0)', verified: true },
      { q: 'A stroke patient was last seen normal at 9:00 PM and found with symptoms at 7:00 AM. Last known well?',
        c: ['7:00 AM', '9:00 PM', 'Midnight', 'Unknown, so skip it'], a: 1,
        why: 'NH 2.24: time last known well is the last time the patient was at their neurological baseline, not when symptoms were found.',
        nh: 'Stroke (2.24)', verified: true },
      { q: 'Why check blood glucose on every suspected stroke?',
        c: ['Stroke raises sugar', 'Hypoglycemia can mimic a stroke', 'It is required before aspirin', 'It predicts bleeding'], a: 1,
        why: 'NH 2.24 lists hypoglycemia as a stroke mimic and says to correct glucose under 60 mg/dL.',
        nh: 'Stroke (2.24)', verified: true },
    ],
  },
  'trial-aemt': {
    id: 'trial-aemt', type: 'exam', level: 2, grants: 'Paramedic', npc: 'drhale', count: 8, misses: 2,
    title: 'AEMT Trial: Earn Your Paramedic', loc: 'JRMA Station', dir: 'home',
    domain: 'Phase 2 boss: AEMT-level protocols',
    urgent: 'Phase two. AEMT protocols, eight questions. Pass and you walk out a paramedic. Miss three and the Binder wins.',
    after: 'Paramedic. Top of the scope. When you are not sure, call medical control. That is what we are here for.',
    monster: { cond: 'The Protocol Binder, Revised', name: 'Binder of Infinite Pages (Revised)', draw: 'binder2', hit: 'loses a tab divider', win: 'is recycled' },
    bank: [
      { q: 'Adult diabetic responds only to pain. Glucose 31 mg/dL. IV attempts failed. Best next medication?',
        c: ['Oral glucose 15 g', 'Glucagon 1 mg IM', 'Naloxone 4 mg IN', 'His usual insulin dose'], a: 1,
        why: 'NH 2.11A: if unable to establish IV access, glucagon 1 mg IM. Oral glucose is an aspiration risk when the patient cannot protect the airway.',
        nh: 'Hypoglycemia - Adult (2.11A)', verified: true },
      { q: 'How does an NH AEMT give dextrose for adult hypoglycemia?',
        c: ['25 g of D50 IV push', 'D10 IV (premixed bag preferred) until baseline mental status and glucose over 60', 'D5W at 100 mL/hr', 'Oral D10 solution'], a: 1,
        why: 'NH 2.11A uses D10 only: premixed bag (preferred) or prefilled syringe, until mental status returns to baseline and glucose is over 60. No pump needed.',
        nh: 'Hypoglycemia - Adult (2.11A)', verified: true },
      { q: 'During a D10 infusion the IV site becomes swollen, cool, and pale. What do you do?',
        c: ['Speed up the flow to push through', 'Stop the infusion and remove the catheter', 'Elevate the arm and continue', 'Hang a second bag'], a: 1,
        why: 'Those are signs of infiltration. Stop, remove, and restart elsewhere. Dextrose in tissue can cause serious injury.',
        nh: 'Not in NH PCP; standard IV practice', verified: true },
      { q: 'Severe asthma not responding to nebulizer treatment. What can an NH AEMT add?',
        c: ['Epinephrine 0.3 mg IM', 'Diphenhydramine 50 mg IV', 'Nitroglycerin 0.4 mg SL', 'Nothing; wait for a paramedic'], a: 0,
        why: 'NH 2.3A AEMT: for severe asthma not responding to treatment, epinephrine 0.3 mg IM (auto-injector preferred, or 1 mg/mL drawn up). Call Medical Control for more doses.',
        nh: 'Asthma/COPD/RAD - Adult (2.3A)', verified: true },
      { q: 'Adult nebulized albuterol dose and repeat interval?',
        c: ['0.25 mg once', '2.5 mg, repeat every 5 minutes for continued symptoms', '25 mg every hour', '0.4 mg every 3 minutes'], a: 1,
        why: 'NH 2.3A: albuterol 2.5 mg by nebulizer, may repeat every 5 minutes for continued symptoms. In NH this is already an EMT order.',
        nh: 'Asthma/COPD/RAD - Adult (2.3A)', verified: true },
      { q: 'Which finding is a contraindication to nitroglycerin for chest pain?',
        c: ['SBP of 150', 'Sildenafil (Viagra) taken last night', 'Pain for 20 minutes', 'Heart rate of 88'], a: 1,
        why: 'NH 3.0: avoid nitroglycerin in any patient who has used a PDE-5 inhibitor. NH also requires SBP over 100.',
        nh: 'Acute Coronary Syndrome - Adult (3.0)', verified: true },
      { q: 'NH AEMT nitroglycerin dose for chest pain, when not contraindicated?',
        c: ['0.04 mg SL', '0.4 mg SL every 3-5 min while SBP stays over 100', '4 mg SL', '0.4 mg IV push'], a: 1,
        why: 'NH 3.0: 0.4 mg SL every 3-5 minutes while symptoms persist and SBP stays over 100.',
        nh: 'Acute Coronary Syndrome - Adult (3.0)', verified: true },
      { q: 'Before an NH AEMT gives nitroglycerin, what must be in place?',
        c: ['A second provider', 'An IV', 'A 12-lead showing STEMI', 'Online Medical Control approval'], a: 1,
        why: 'NH 3.0 AEMT: IV must be established before administration of nitroglycerin.',
        nh: 'Acute Coronary Syndrome - Adult (3.0)', verified: true },
      { q: 'Opioid overdose: pulse present, respiratory rate 4. What is the goal of naloxone?',
        c: ['Full wakefulness', 'Adequate spontaneous breathing', 'Normal pupils', 'Heart rate over 100'], a: 1,
        why: 'NH 2.17A: titrate until respiratory depression resolves, not necessarily until the patient wakes up.',
        nh: 'Opioid Overdose - Adult (2.17A)', verified: true },
      { q: 'Adult IM epinephrine dose for anaphylaxis (drawn up)?',
        c: ['0.3 mg of 1 mg/mL (1:1,000) IM', '1 mg of 0.1 mg/mL IV push', '0.03 mg IM', '3 mg IM'], a: 0,
        why: 'NH: 1 mg/mL, 0.3 mg IM in the lateral thigh, repeat every 5 minutes until symptoms resolve. The 0.1 mg/mL concentration is not for IM anaphylaxis.',
        nh: 'Allergic Reaction/Anaphylaxis - Adult (2.2A); Formulary (Appendix 2)', verified: true },
      { q: 'How must you confirm supraglottic airway placement?',
        c: ['Fogging in the tube', 'Waveform capnography', 'Improved skin color', 'A colorimetric CO2 detector alone'], a: 1,
        why: 'NH 6.1: confirm and monitor every airway device with quantitative waveform capnography. Colorimetric detectors are not an approved alternative.',
        nh: 'Supraglottic Airways (5.12); Capnography (6.1)', verified: true },
      { q: 'Preferred adult IO insertion sites?',
        c: ['Sternum and skull', 'Proximal humerus or proximal tibia', 'Distal radius', 'Iliac crest only'], a: 1,
        why: 'Proximal humerus and proximal tibia are the usual adult sites. NH 6.4: use the sites you are trained on for your device.',
        nh: 'Intraosseous Access (6.4)', verified: true },
      { q: 'Which is an absolute contraindication to CPAP under NH protocol?',
        c: ['Wheezing', 'Unresponsive', 'SpO2 of 90%', 'History of COPD'], a: 1,
        why: 'NH 5.4: no CPAP in arrest, agonal breathing, unresponsive patients, vomiting or upper GI bleed, distress from trauma, or suspected pneumothorax.',
        nh: 'Continuous Positive Airway Pressure (CPAP) (5.4)', verified: true },
      { q: 'Trauma patient in hemorrhagic shock, no head injury. NH AEMT fluid goal?',
        c: ['Liters until BP is normal', 'Small boluses (about 250 mL) to a radial pulse or clear mentation', 'No fluids ever', 'Oral fluids'], a: 1,
        why: 'NH 4.6: small boluses to a coherent mental status or palpable radial pulse. Max 2 L without Medical Control. Do not delay transport for IV access.',
        nh: 'Shock - Traumatic (4.6)', verified: true },
      { q: 'Head-injured trauma patient. NH AEMT blood pressure goal?',
        c: ['SBP over 90', 'SBP over 110', 'MAP over 50', 'No fluids with a head injury'], a: 1,
        why: 'NH 4.9: small boluses (about 250 mL) to keep SBP over 110. Low pressure worsens brain injury.',
        nh: 'Traumatic Brain Injury (4.9)', verified: true },
    ],
  },
  'trial-medic': {
    id: 'trial-medic', type: 'exam', level: 3, grants: 'Legend of JRMA', npc: 'drhale', count: 10, misses: 2,
    title: 'Paramedic Trial: Become a Legend', loc: 'JRMA Station', dir: 'home',
    domain: 'Final boss phase 2: Paramedic-level protocols',
    urgent: 'The final trial. Ten paramedic questions. Pass, and they will tell stories about you at shift change.',
    after: 'Legend of JRMA. The binder bows to you. Now go teach the new people.',
    monster: { cond: 'The Protocol Binder Supreme', name: 'Binder Supreme (Laminated Tabs)', draw: 'binder3', hit: 'loses its lamination', win: 'is shredded, then recycled' },
    bank: [
      { q: 'Adult VF arrest after shocks. First dose of amiodarone?',
        c: ['150 mg IV/IO', '300 mg IV/IO', '1 mg/kg IV/IO', '5 mg/kg IV/IO'], a: 1,
        why: '300 mg first dose, 150 mg second. NH follows ACLS for anti-dysrhythmics.',
        nh: 'Cardiac Arrest - Adult (3.2A): anti-dysrhythmic per ACLS', verified: true },
      { q: 'Epinephrine dose and timing in adult cardiac arrest per NH?',
        c: ['0.3 mg IM every 5 min', '1 mg IV/IO after the first 2-min cycle, then every other cycle', '1 mg IV/IO every 10 min', '0.1 mg IV every minute'], a: 1,
        why: 'NH 3.2A: after the first 2-minute cycle, epinephrine 1 mg IV (0.1 mg/mL), then repeat every other cycle.',
        nh: 'Cardiac Arrest - Adult (3.2A)', verified: true },
      { q: 'NH adult arrest: when does the paramedic consider intubation?',
        c: ['Immediately, before the first shock', 'After 4 cycles (8 minutes), without stopping compressions', 'Only after ROSC', 'Never in the field'], a: 1,
        why: 'NH 3.2A: after 4 cycles (8 minutes), consider endotracheal intubation without interrupting compressions. BVM or passive oxygen before that.',
        nh: 'Cardiac Arrest - Adult (3.2A); Team Focused CPR (3.6)', verified: true },
      { q: 'Refractory VF after 3 shocks, and you have only one monitor. NH option?',
        c: ['Stop and transport', 'Change the pads from anterior-apex to anterior-posterior', 'Lower the energy', 'Give adenosine'], a: 1,
        why: 'NH 3.2A: with a second manual defibrillator, consider double sequential defibrillation (6.2). Without one, change the pad vector to anterior-posterior.',
        nh: 'Cardiac Arrest - Adult (3.2A); Double Sequential Defibrillation (6.2)', verified: true },
      { q: 'During CPR, ETCO2 reads 14 mmHg. What does NH say that suggests?',
        c: ['ROSC', 'Compressions are not high quality', 'Esophageal intubation is ruled out', 'Hyperventilation'], a: 1,
        why: 'NH 6.1: high-quality compressions produce ETCO2 of at least 20 mmHg. Push harder, faster, or swap compressors. A sudden sustained rise suggests ROSC.',
        nh: 'Capnography (6.1)', verified: true },
      { q: 'Post-ROSC oxygen saturation target per NH?',
        c: ['100% at all times', '94-98%', '85-88%', 'No oxygen'], a: 1,
        why: 'NH 3.4: titrate oxygen to 94-98%. Avoid both hypoxia and hyperoxia.',
        nh: 'Post Resuscitative Care (3.4)', verified: true },
      { q: 'Post-ROSC hypotension. NH adult target?',
        c: ['SBP over 70', 'SBP over 90 or MAP at least 65', 'SBP over 140', 'MAP over 100'], a: 1,
        why: 'NH 3.4: SBP over 90 or MAP at least 65. 250 mL boluses (max 2 L), then vasopressors.',
        nh: 'Post Resuscitative Care (3.4)', verified: true },
      { q: 'Unstable symptomatic bradycardia. NH atropine dosing?',
        c: ['0.5 mg IV, max 1 mg', '1 mg IV every 3-5 min, max 3 mg', '2 mg IV once', '0.02 mg/kg, no maximum'], a: 1,
        why: 'NH 3.1A: consider atropine 1 mg IV every 3-5 minutes to a max of 3 mg. Do not let it delay pacing in high-degree block.',
        nh: 'Bradycardia - Adult (3.1A)', verified: true },
      { q: 'Bradycardia when pacing fails. NH epinephrine infusion rate?',
        c: ['2-10 mcg/min', '20-50 mcg/min', '0.1-0.5 mcg/min', '1 mg/min'], a: 0,
        why: 'NH 3.1A: epinephrine 2-10 mcg/min via pump. Norepinephrine 1-80 mcg/min and push-dose epinephrine are also listed.',
        nh: 'Bradycardia - Adult (3.1A)', verified: true },
      { q: 'Sedation for transcutaneous pacing per NH?',
        c: ['Not allowed', 'Midazolam 2.5 mg IV, may repeat once in 5 min', 'Fentanyl 500 mcg IV', 'A propofol drip'], a: 1,
        why: 'NH 3.1A: sedate before or during pacing if feasible: midazolam 2.5 mg IV (or 5 mg IM/IN), lorazepam, diazepam, or low-dose ketamine.',
        nh: 'Bradycardia - Adult (3.1A)', verified: true },
      { q: 'How do you confirm mechanical capture during transcutaneous pacing?',
        c: ['Carotid pulse', 'Femoral pulse or a matching SpO2 waveform', 'Muscle twitching', 'Pacer spikes on the monitor'], a: 1,
        why: 'Pacing makes muscles twitch, which can mimic a carotid pulse. Check the femoral pulse. Spikes alone show electrical output, not capture.',
        nh: 'Not in NH PCP; ACLS practice', verified: true },
      { q: 'Stable narrow-complex regular tachycardia (SVT), vagal maneuvers failed. NH adenosine?',
        c: ['6 mg rapid IV push, may repeat 12 mg in 1-2 min', '12 mg slow IV over 2 min', '3 mg IM', '6 mg IV over 10 min'], a: 0,
        why: 'NH 3.5A: adenosine 6 mg rapid IV push, may repeat at 12 mg in 1-2 minutes if no conversion.',
        nh: 'Tachycardia - Adult (3.5A)', verified: true },
      { q: 'Unstable tachycardia with a pulse (hypotension, altered). Treatment?',
        c: ['Unsynchronized defibrillation', 'Synchronized cardioversion', 'Adenosine only', 'Observe and transport'], a: 1,
        why: 'NH 3.5A: if hemodynamically unstable, synchronized cardioversion. Sedate if time and BP allow.',
        nh: 'Tachycardia - Adult (3.5A)', verified: true },
      { q: 'Polymorphic VT with a prolonged QT (torsades de pointes). NH drug?',
        c: ['Magnesium sulfate 1-2 g IV over 5 min', 'Adenosine 6 mg', 'Atropine 1 mg', 'Diltiazem'], a: 0,
        why: 'NH 3.5A: consider magnesium sulfate 1-2 g IV over 5 minutes. Defibrillate if pulseless.',
        nh: 'Tachycardia - Adult (3.5A)', verified: true },
      { q: 'ST elevation in II, III, and aVF. Which STEMI, and what does NH suggest next?',
        c: ['Anterior; give nitro', 'Inferior; consider a right-sided ECG', 'Lateral; skip aspirin', 'Septal; no action'], a: 1,
        why: 'Inferior. NH 6.0: for a suspected inferior MI, consider a right-sided ECG (V4R) to look for right ventricular involvement.',
        nh: 'Acute Coronary Syndrome - Adult (3.0); 12 Lead Acquisition (6.0)', verified: true },
      { q: 'Accepted adult needle decompression sites for tension pneumothorax per NH?',
        c: ['2nd intercostal space midclavicular, or 4th-5th intercostal space anterior axillary', 'Sternal notch', '8th intercostal space posterior', 'Below the xiphoid'], a: 0,
        why: 'NH 4.8: 2nd intercostal midclavicular, or 4th to 5th intercostal anterior axillary, as trained.',
        nh: 'Thoracic Injuries (4.8)', verified: true },
      { q: 'Dialysis patient with peaked T waves and a wide QRS. NH first-line drug?',
        c: ['Amiodarone', 'Calcium (gluconate 3 g or chloride 1 g IV/IO)', 'Adenosine', 'Furosemide'], a: 1,
        why: 'NH 2.9: calcium is the first-line agent for hyperkalemia. Calcium gluconate 3 g (preferred with a pulse) or calcium chloride 1 g, in 50-100 mL over 5-10 minutes.',
        nh: 'Hyperkalemia (2.9)', verified: true },
      { q: 'Pediatric cardiac arrest epinephrine dose per NH?',
        c: ['0.1 mg/kg IV/IO', '0.01 mg/kg IV/IO, every other cycle', '1 mg IV/IO regardless of weight', '0.001 mg/kg IV/IO'], a: 1,
        why: 'NH 3.2P: 0.01 mg/kg (0.1 mL/kg of 0.1 mg/mL) IV/IO, repeated every other cycle. Use a length-based tape.',
        nh: 'Cardiac Arrest - Pediatric (3.2P)', verified: true },
      { q: 'Adult in status epilepticus, no IV. NH midazolam dose IM or IN?',
        c: ['1 mg', '2.5 mg', '10 mg, repeat every 5 min as needed', '50 mg'], a: 2,
        why: 'NH 2.20A: midazolam 10 mg IM or IN, repeat every 5 minutes as needed.',
        nh: 'Seizures - Adult (2.20A)', verified: true },
    ],
  },
};
